(()=>{
'use strict';
const API='https://floodguard-rescue-backend.onrender.com',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={pending:'Chưa xác minh',corroborated:'Có xác nhận cộng đồng',disputed:'Cần kiểm tra lại',verified:'Đã xác minh',expired:'Đã hết hạn',rejected:'Không được chấp nhận',resolved:'Đã kết thúc'};
const severity={shallow:'Nước đọng / ngập nhẹ',deep:'Ngập rõ trên mặt đường',blocked:'Cản trở di chuyển',unknown:'Chưa xác định mức ngập'};
let panel=null,me={authenticated:false,admin:false,points:0},mode='feed',reports=[],miniMap=null,pins=null,chosen=null,lastButton=null,busy=false,requestId=0,photo=null;
const standalone=!!document.querySelector('[data-community-page]');
async function api(path,options={}){if(typeof window.FGCommunityAPI==='function')return window.FGCommunityAPI('/api/community/'+path,options);const r=await fetch(API+'/api/community/'+path,{...options,headers:{'Content-Type':'application/json'},cache:'no-store',signal:AbortSignal.timeout(20000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Không kết nối được hệ thống.');return d}
const el=id=>panel?.querySelector('#'+id);
function message(text,error=false){const n=el('cgMessage');if(n){n.textContent=text;n.classList.toggle('error',error)}}
function requireLogin(){if(me.authenticated)return true;message('Đăng nhập FloodGuard để gửi báo cáo và xác nhận thông tin.',true);el('cgLogin').hidden=false;return false}
function layout(){return `<header class="cg-head"><div><span class="cg-kicker">FLOODGUARD · CỘNG ĐỒNG</span><h2 id="cgTitle">Cùng cập nhật tình trạng đường</h2><p>Báo cáo điều bạn thấy. Giúp người khác hiểu khu vực trước khi đi.</p></div>${standalone?'<a class="cg-close" href="./" aria-label="Về trang chủ">←</a>':'<button type="button" class="cg-close" data-close aria-label="Đóng cộng đồng">×</button>'}</header>
<div class="cg-scroll"><div class="cg-stats"><div><span>Điểm đóng góp</span><b id="cgPoints">—</b></div><div><span>Huy hiệu</span><b id="cgBadge">—</b></div><div><span>Đổi quà</span><b>Chưa mở</b></div></div>
<div class="cg-tabs" role="group" aria-label="Mục cộng đồng"><button data-mode="feed" aria-pressed="true">Bản tin</button><button data-mode="mine" aria-pressed="false">Của tôi</button><button data-mode="rewards" aria-pressed="false">Điểm & quà</button><button data-mode="review" id="cgReviewTab" hidden aria-pressed="false">Duyệt báo cáo</button></div>
<p id="cgMessage" class="cg-message" role="status" aria-live="polite"></p><a id="cgLogin" class="cg-login" href="./?login=1" hidden>Đăng nhập FloodGuard →</a>
<div id="cgContent"><div class="cg-toolbar"><div><h3>Thông tin gần đây</h3><p>Hiển thị trong tối đa 3 giờ. Xem thời điểm và trạng thái trước khi dùng.</p></div><button id="cgNew" class="cg-primary" type="button">+ Báo cáo ngập</button></div>
<div id="cgMap" class="cg-map" aria-label="Bản đồ báo cáo ngập"></div>
<form id="cgForm" class="cg-form" hidden><div class="cg-form-head"><h3>Báo cáo tại hiện trường</h3><button type="button" id="cgCancel" class="cg-secondary">Đóng biểu mẫu</button></div><p>Chỉ thao tác khi đã dừng ở nơi an toàn. Không đi vào vùng ngập để chụp ảnh.</p>
<div class="cg-location"><button id="cgLocate" type="button" class="cg-secondary">Dùng vị trí hiện tại</button><span id="cgLocation">Hoặc bấm một vị trí trên bản đồ.</span></div>
<label for="cgPlace">Tên đường / địa điểm</label><input id="cgPlace" maxlength="120" minlength="3" required placeholder="Ví dụ: đoạn đường gần giao lộ…">
<label for="cgSeverity">Tình trạng quan sát được</label><select id="cgSeverity"><option value="unknown">Chưa xác định mức ngập</option><option value="shallow">Nước đọng / ngập nhẹ</option><option value="deep">Ngập rõ trên mặt đường</option><option value="blocked">Cản trở di chuyển</option></select>
<label for="cgDescription">Mô tả thêm</label><textarea id="cgDescription" maxlength="500" rows="3" placeholder="Đoạn ngập, hướng đường, tình trạng quan sát…"></textarea>
<label for="cgPhoto">Ảnh hiện trường (không bắt buộc)</label><input id="cgPhoto" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><p class="cg-small">Ảnh được giảm kích thước và bỏ dữ liệu vị trí ẩn. Tránh ảnh rõ mặt người, biển số hoặc thông tin cá nhân.</p><img id="cgPreview" class="cg-preview" alt="Ảnh báo cáo đã chọn" hidden>
<label class="cg-consent"><input id="cgConsent" type="checkbox" required><span>Tôi đồng ý chia sẻ địa điểm, mô tả và ảnh báo cáo với cộng đồng FloodGuard.</span></label>
<button id="cgSubmit" class="cg-primary" type="submit">Gửi báo cáo</button><p class="cg-small">Tối đa 3 báo cáo / 24 giờ. Báo cáo có ảnh được xác minh nhận tối đa 10 điểm; gửi báo cáo chưa được cộng điểm.</p></form>
<div class="cg-list-head"><span id="cgCount"></span><button id="cgRefresh" type="button" class="cg-secondary">Làm mới</button></div><div id="cgList" class="cg-list"></div></div>
<section id="cgRewards" class="cg-rewards" hidden><h3>Điểm ghi nhận đóng góp hữu ích</h3><div class="cg-rule"><b>Tối đa 10 điểm / báo cáo</b><p>Có ảnh hiện trường và được quản trị viên xác minh. Không cộng theo mức độ nguy hiểm.</p></div><div class="cg-rule"><b>Tối đa 2 điểm / xác nhận</b><p>Xác nhận phù hợp tại gần hiện trường, khi báo cáo được quản trị viên chấp nhận.</p></div><div class="cg-rule"><b>Giới hạn 30 điểm / 24 giờ</b><p>Ảnh trùng, báo cáo lặp và tự xác nhận không được tính thêm.</p></div><div class="cg-rule"><b>Huy hiệu đóng góp</b><p>30 điểm: Người đóng góp · 100 điểm: Người đồng hành.</p></div><div class="cg-gifts"><h4>Voucher sẽ mở khi có đối tác</h4><p>Hiện chưa có quà hoặc mã giảm giá để đổi. Điểm hiện dùng để ghi nhận đóng góp, chưa có giá trị quy đổi.</p></div><h4>Lịch sử điểm của bạn</h4><div id="cgHistory"></div></section>
<footer class="cg-note">Báo cáo cộng đồng được hiển thị riêng với kết quả mô hình. Thông tin chưa xác minh không phải số đo chính thức và không tự thay đổi dự báo hoặc lộ trình.</footer></div>`}
function build(){if(panel)return;if(standalone){panel=document.querySelector('[data-community-page]');panel.className='cg-panel cg-page';panel.innerHTML=layout()}else{panel=document.createElement('dialog');panel.className='cg-panel';panel.setAttribute('aria-labelledby','cgTitle');panel.innerHTML=layout();document.body.appendChild(panel);panel.addEventListener('close',()=>{requestId++;lastButton?.focus()})}bind()}
async function open(button){build();lastButton=button||lastButton;if(!standalone&&!panel.open)panel.showModal();message('Đang tải dữ liệu cộng đồng…');await refresh();setTimeout(()=>miniMap?.invalidateSize(),100)}
function mapInit(){if(miniMap||!window.L)return;miniMap=L.map(el('cgMap')).setView([10.78,106.69],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(miniMap);pins=L.layerGroup().addTo(miniMap);miniMap.on('click',event=>{if(!el('cgForm').hidden)setLocation(event.latlng.lat,event.latlng.lng)})}
function setLocation(lat,lon){chosen={lat,lon};el('cgLocation').textContent=`Đã chọn ${lat.toFixed(4)}, ${lon.toFixed(4)}`;miniMap?.setView([lat,lon],16)}
function gps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Thiết bị không hỗ trợ định vị.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(new Error('Chưa lấy được vị trí. Hãy cho phép định vị khi xác nhận báo cáo.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
function draw(){mapInit();pins?.clearLayers();reports.forEach(r=>{if(!pins)return;L.circleMarker([r.lat,r.lon],{radius:7,color:r.status==='verified'?'#20795d':'#c17b16',fillOpacity:.8}).addTo(pins).bindTooltip(esc(r.place))});el('cgCount').textContent=reports.length?`${reports.length} báo cáo`:'Chưa có báo cáo';el('cgList').innerHTML=reports.length?reports.map(r=>{
const closed=['expired','verified','rejected','resolved'].includes(r.status),when=new Date(r.created_at).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});
return `<article class="cg-report" data-report="${r.id}"><div class="cg-report-top"><span class="cg-status ${r.status}">${labels[r.status]||labels.pending}</span><time>${when}</time></div><h4>${esc(r.place)}</h4><p>${severity[r.severity]||''}</p>${r.description?`<p>${esc(r.description)}</p>`:''}<small>${r.confirmations} xác nhận · ${r.disagreements} ý kiến khác${r.mine?' · Báo cáo của bạn':''}</small>${r.review_note?`<p class="cg-small">Ghi chú duyệt: ${esc(r.review_note)}</p>`:''}<div class="cg-report-actions"><button data-map="${r.id}" type="button">Xem vị trí</button>${r.has_photo?`<button data-photo="${r.id}" type="button">Xem ảnh</button>`:''}${!closed&&!r.mine&&!r.voted?`<button data-confirm="${r.id}" data-agrees="true" type="button">Tôi thấy vẫn ngập</button><button data-confirm="${r.id}" data-agrees="false" type="button">Thông tin đã thay đổi</button>`:''}</div><div class="cg-photo-slot"></div>${me.admin&&mode==='review'?`<label for="note-${r.id}">Ghi chú kiểm tra</label><textarea id="note-${r.id}" maxlength="250" rows="2"></textarea><div class="cg-report-actions">${r.status!=='verified'?`<button data-review="${r.id}" data-action="verified" type="button">Xác minh & cộng điểm</button><button data-review="${r.id}" data-action="rejected" type="button">Không chấp nhận</button>`:''}<button data-review="${r.id}" data-action="resolved" type="button">Đã kết thúc</button></div>`:''}</article>`}).join(''):`<div class="cg-empty"><h4>${mode==='mine'?'Bạn chưa có báo cáo':'Chưa có báo cáo trong mục này'}</h4><p>${mode==='review'?'Các báo cáo đang chờ duyệt sẽ xuất hiện tại đây.':'Bạn có thể đóng góp tình trạng đường khi quan sát được tại nơi an toàn.'}</p></div>`}
async function refresh(){const id=++requestId;try{const info=await api('me');if(id!==requestId)return;me=info;el('cgPoints').textContent=me.authenticated?me.points:'—';el('cgBadge').textContent=me.authenticated?me.badge:'Đăng nhập để xem';el('cgReviewTab').hidden=!me.admin;el('cgLogin').hidden=me.authenticated;el('cgHistory').innerHTML=me.history?.length?me.history.map(p=>`<p><b>+${p.points}</b> · ${p.reason==='report'?'Báo cáo được xác minh':'Xác nhận hữu ích'} · ${new Date(p.created_at).toLocaleDateString('vi-VN')}</p>`).join(''):'<p>Chưa có điểm được ghi nhận.</p>';if(mode==='rewards'){message('');return}if(mode==='mine'&&!me.authenticated){reports=[];draw();message('Đăng nhập để xem lịch sử đóng góp.');return}const d=await api('feed?mode='+mode);if(id!==requestId)return;reports=d.reports||[];draw();message('')}catch(e){if(id===requestId)message(e.message,true)}}
async function compress(file){if(!file)return null;if(file.size>12*1024*1024)throw new Error('Ảnh cần nhỏ hơn 12 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Chọn ảnh JPG, PNG hoặc WebP.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>25000000)throw new Error('Ảnh quá lớn. Hãy chọn ảnh có độ phân giải thấp hơn.');const scale=Math.min(1,960/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);for(const quality of [.75,.55,.35,.2]){const value=canvas.toDataURL('image/jpeg',quality);if(value.length<=180000)return value}throw new Error('Ảnh còn quá lớn sau khi nén. Hãy chọn ảnh khác.')}finally{bitmap.close()}}
function bind(){panel.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){panel.close();return}if(b.dataset.mode){if(b.dataset.mode==='review'&&!me.admin)return;mode=b.dataset.mode;panel.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));el('cgContent').hidden=mode==='rewards';el('cgRewards').hidden=mode!=='rewards';el('cgForm').hidden=true;await refresh();miniMap?.invalidateSize();return}if(b.dataset.map){const r=reports.find(x=>x.id===b.dataset.map);if(r)miniMap?.setView([r.lat,r.lon],16);el('cgMap').scrollIntoView({block:'center',behavior:'smooth'});return}if(b.dataset.photo){if(!requireLogin())return;b.disabled=true;try{const d=await api('photo/'+b.dataset.photo);b.closest('.cg-report').querySelector('.cg-photo-slot').innerHTML=`<img alt="Ảnh hiện trường của báo cáo" src="${d.photo}" class="cg-report-photo">`}catch(e){message(e.message,true)}finally{b.disabled=false}return}if(b.dataset.confirm){if(!requireLogin())return;b.disabled=true;try{message('Đang lấy vị trí để xác nhận…');const location=await gps();await api('confirm',{method:'POST',body:JSON.stringify({report_id:b.dataset.confirm,agrees:b.dataset.agrees==='true',...location})});await refresh();message('Đã ghi nhận. Điểm chỉ được cộng khi báo cáo được duyệt.')}catch(e){message(e.message,true)}finally{b.disabled=false}return}if(b.dataset.review){b.disabled=true;try{await api('review',{method:'POST',body:JSON.stringify({report_id:b.dataset.review,action:b.dataset.action,note:el('note-'+b.dataset.review)?.value||''})});await refresh();message('Đã xử lý báo cáo.')}catch(e){message(e.message,true)}finally{b.disabled=false}}});
el('cgNew').onclick=()=>{if(!requireLogin())return;el('cgForm').hidden=false;el('cgForm').scrollIntoView({block:'start',behavior:'smooth'});miniMap?.invalidateSize()};el('cgCancel').onclick=()=>{el('cgForm').hidden=true};el('cgRefresh').onclick=refresh;
el('cgLocate').onclick=async()=>{const b=el('cgLocate');b.disabled=true;try{const p=await gps();setLocation(p.lat,p.lon);message('Đã chọn vị trí hiện tại.')}catch(e){message(e.message,true)}finally{b.disabled=false}};
el('cgPhoto').onchange=async()=>{el('cgSubmit').disabled=true;photo=null;el('cgPreview').hidden=true;try{photo=await compress(el('cgPhoto').files[0]);if(photo){el('cgPreview').src=photo;el('cgPreview').hidden=false}}catch(e){el('cgPhoto').value='';message(e.message,true)}finally{el('cgSubmit').disabled=false}};
el('cgForm').onsubmit=async event=>{event.preventDefault();if(busy||!requireLogin())return;if(!chosen)return message('Chọn vị trí trên bản đồ hoặc dùng vị trí hiện tại.',true);busy=true;el('cgSubmit').disabled=true;try{const d=await api('reports',{method:'POST',body:JSON.stringify({...chosen,place:el('cgPlace').value,description:el('cgDescription').value,severity:el('cgSeverity').value,photo,share_consent:el('cgConsent').checked})});el('cgForm').reset();el('cgForm').hidden=true;photo=null;chosen=null;el('cgPreview').hidden=true;el('cgLocation').textContent='Hoặc bấm một vị trí trên bản đồ.';await refresh();message(d.message)}catch(e){message(e.message,true)}finally{busy=false;el('cgSubmit').disabled=false}};
}
function entry(){const nav=document.querySelector('#fg3App .fg3-nav');if(nav&&!document.getElementById('fgCommunityBtn')){const b=document.createElement('button');b.id='fgCommunityBtn';b.className='fg3-btn hide-mobile';b.type='button';b.setAttribute('aria-label','Đóng góp cộng đồng');b.title='Đóng góp cộng đồng';b.innerHTML='<span class="fg14-nav-ico" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 4v2"/></svg></span><span class="fg14-nav-label">Cộng đồng</span>';b.onclick=()=>open(b);nav.appendChild(b)}const grid=document.querySelector('#fg14MoreSheet .fg14-more-grid');if(grid&&!grid.querySelector('[data-community-entry]')){const b=document.createElement('button');b.type='button';b.className='fg14-more-item';b.dataset.communityEntry='1';b.innerHTML='<strong>◎</strong><div><b>Đóng góp cộng đồng</b><span>Báo cáo ngập, xác minh và điểm</span></div>';b.onclick=()=>{document.getElementById('fg14MoreSheet')?.classList.remove('show');document.getElementById('fg14MoreBack')?.classList.remove('show');open(b)};grid.appendChild(b)}}
if(standalone)open();else{entry();const observer=new MutationObserver(entry);observer.observe(document.body,{subtree:true,childList:true});setTimeout(()=>observer.disconnect(),30000)}
})();
