(()=>{
'use strict';
const API='https://floodguard-rescue-backend.onrender.com',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={pending:'Chưa xác minh',corroborated:'Có xác nhận cộng đồng',disputed:'Cần kiểm tra lại',verified:'Đã xác minh',expired:'Đã hết hạn',rejected:'Không được chấp nhận',resolved:'Đã kết thúc'};
const severity={shallow:'Nước đọng / ngập nhẹ',deep:'Ngập rõ trên mặt đường',blocked:'Cản trở di chuyển',unknown:'Chưa xác định mức ngập'};
let panel=null,me={authenticated:false,admin:false,points:0},mode='feed',reports=[],miniMap=null,pins=null,chosen=null,lastButton=null,busy=false,requestId=0,photo=null,photoProcessing=false,photoError='',photoVersion=0,draftPin=null,redeemBusy=false,rewardRequest=null;
const standalone=!!document.querySelector('[data-community-page]');
let standaloneAuth=null;
async function standaloneSession(){if(!standalone)return null;if(!standaloneAuth)standaloneAuth=(async()=>{if(!window.supabase?.createClient)throw Error('Chưa tải được kết nối tài khoản. Hãy tải lại trang.');const r=await fetch(API+'/api/public-config',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.supabase?.url||!d.supabase?.anon_key)throw Error('Chưa kết nối được tài khoản.');return window.supabase.createClient(d.supabase.url,d.supabase.anon_key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})})();try{const client=await standaloneAuth;return (await client.auth.getSession()).data.session}catch(e){standaloneAuth=null;throw e}}
async function api(path,options={}){if(typeof window.FGCommunityAPI==='function')return window.FGCommunityAPI('/api/community/'+path,options);const session=await standaloneSession(),headers={'Content-Type':'application/json',...(session?.access_token?{Authorization:'Bearer '+session.access_token}:{})};const r=await fetch(API+'/api/community/'+path,{...options,headers,cache:'no-store',signal:options.signal||(typeof AbortSignal.timeout==='function'?AbortSignal.timeout(20000):undefined)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Không kết nối được hệ thống.');return d}
const el=id=>panel?.querySelector('#'+id);
function message(text,error=false){const n=el('cgMessage');if(n){n.textContent=text;n.classList.toggle('error',error)}}
function submitMessage(text,error=false){const n=el('cgSubmitStatus');if(n){n.textContent=text;n.classList.toggle('error',error);n.hidden=!text}}
function requireLogin(){if(me.authenticated)return true;message('Đăng nhập FloodGuard để gửi báo cáo và xác nhận thông tin.',true);el('cgLogin').hidden=false;return false}
function layout(){return `<header class="cg-head"><div><span class="cg-kicker">FLOODGUARD · CỘNG ĐỒNG</span><h2 id="cgTitle">Cùng cập nhật tình trạng đường</h2><p>Báo cáo điều bạn thấy. Giúp người khác hiểu khu vực trước khi đi.</p></div>${standalone?'<a class="cg-close" href="./" aria-label="Về trang chủ">←</a>':'<button type="button" class="cg-close" data-close aria-label="Đóng cộng đồng">×</button>'}</header>
<div class="cg-scroll"><div class="cg-stats"><div><span>Điểm có thể đổi</span><b id="cgPoints">—</b></div><div><span>Huy hiệu</span><b id="cgBadge">—</b></div><div><span>Đổi quà</span><b id="cgVoucherCount">—</b></div></div>
<div class="cg-tabs" role="group" aria-label="Mục cộng đồng"><button data-mode="feed" aria-pressed="true">Bản tin</button><button data-mode="mine" aria-pressed="false">Của tôi</button><button data-mode="rewards" aria-pressed="false">Điểm & quà</button></div>
<p id="cgMessage" class="cg-message" role="status" aria-live="polite"></p><a id="cgLogin" class="cg-login" href="./?login=1" hidden>Đăng nhập FloodGuard →</a>
<div id="cgContent"><div class="cg-toolbar"><div><h3>Thông tin gần đây</h3><p>Hiển thị trong tối đa 3 giờ. Xem thời điểm và trạng thái trước khi dùng.</p></div><button id="cgNew" class="cg-primary" type="button">+ Báo cáo ngập</button></div>
<div id="cgMap" class="cg-map" aria-label="Bản đồ báo cáo ngập"></div>
<form id="cgForm" class="cg-form" novalidate hidden><div class="cg-form-head"><h3>Báo cáo tại hiện trường</h3><button type="button" id="cgCancel" class="cg-secondary">Đóng biểu mẫu</button></div><p>Chỉ thao tác khi đã dừng ở nơi an toàn. Không đi vào vùng ngập để chụp ảnh.</p>
<div class="cg-location"><button id="cgLocate" type="button" class="cg-secondary">Dùng vị trí hiện tại</button><button id="cgChooseMap" type="button" class="cg-secondary">Chọn trên bản đồ</button><span id="cgLocation">Chưa chọn vị trí báo cáo.</span></div>
<label for="cgPlace">Tên đường / địa điểm</label><input id="cgPlace" maxlength="120" minlength="3" required placeholder="Ví dụ: đoạn đường gần giao lộ…">
<label for="cgSeverity">Tình trạng quan sát được</label><select id="cgSeverity"><option value="unknown">Chưa xác định mức ngập</option><option value="shallow">Nước đọng / ngập nhẹ</option><option value="deep">Ngập rõ trên mặt đường</option><option value="blocked">Cản trở di chuyển</option></select>
<label for="cgDescription">Mô tả thêm</label><textarea id="cgDescription" maxlength="500" rows="3" placeholder="Đoạn ngập, hướng đường, tình trạng quan sát…"></textarea>
<label for="cgPhoto">Ảnh hiện trường (không bắt buộc)</label><input id="cgPhoto" type="file" accept="image/*"><p id="cgPhotoStatus" class="cg-small" role="status" aria-live="polite">Chọn ảnh từ thư viện hoặc máy ảnh.</p><button id="cgRemovePhoto" type="button" class="cg-secondary" hidden>Bỏ ảnh đã chọn</button><p class="cg-small">Ảnh được giảm kích thước và bỏ dữ liệu vị trí ẩn. Tránh ảnh rõ mặt người, biển số hoặc thông tin cá nhân.</p><img id="cgPreview" class="cg-preview" alt="Ảnh báo cáo đã chọn" hidden>
<label class="cg-consent"><input id="cgConsent" type="checkbox" required><span>Tôi đồng ý chia sẻ địa điểm, mô tả và ảnh báo cáo với cộng đồng FloodGuard.</span></label>
<p id="cgSubmitStatus" class="cg-submit-status" role="alert" aria-live="assertive" hidden></p><button id="cgSubmit" class="cg-primary" type="submit" aria-describedby="cgSubmitStatus">Gửi báo cáo</button><p class="cg-small">Tối đa 3 báo cáo / 24 giờ. Báo cáo có ảnh được xác minh nhận tối đa 10 điểm; gửi báo cáo chưa được cộng điểm.</p></form>
<div class="cg-list-head"><span id="cgCount"></span><button id="cgRefresh" type="button" class="cg-secondary">Làm mới</button></div><div id="cgList" class="cg-list"></div></div>
<section id="cgRewards" class="cg-rewards" hidden><h3>Điểm ghi nhận đóng góp hữu ích</h3><div class="cg-rule"><b>Tối đa 10 điểm / báo cáo</b><p>Có ảnh hiện trường và được quản trị viên xác minh. Không cộng theo mức độ nguy hiểm.</p></div><div class="cg-rule"><b>Tối đa 2 điểm / xác nhận</b><p>Xác nhận phù hợp tại gần hiện trường, khi báo cáo được quản trị viên chấp nhận.</p></div><div class="cg-rule"><b>Giới hạn 30 điểm / 24 giờ</b><p>Ảnh trùng, báo cáo lặp và tự xác nhận không được tính thêm.</p></div><section class="cg-badges"><h4>Các mốc huy hiệu</h4><p>Mốc tính theo tổng điểm đóng góp đã được ghi nhận, không gồm thưởng mốc. Đổi voucher không làm tụt huy hiệu. Mỗi mốc thưởng một lần, ngoài giới hạn điểm báo cáo hằng ngày.</p><p id="cgBadgeProgress"></p><div id="cgBadgeTiers" class="cg-tier-grid"></div></section><section class="cg-gifts"><h4>Đổi voucher bằng điểm</h4><p>Voucher cài sẵn hiện là bản thử nghiệm, không có giá trị giảm giá tại cửa hàng hoặc trạm sạc. Đổi voucher sẽ trừ điểm trong tài khoản.</p><p id="cgRewardStatus" role="status" aria-live="polite"></p><div id="cgVoucherCatalog" class="cg-voucher-grid"></div><h4>Voucher của tôi</h4><div id="cgMyVouchers"></div></section><h4>Lịch sử điểm của bạn</h4><div id="cgHistory"></div></section>
<footer class="cg-note">Báo cáo cộng đồng được hiển thị riêng với kết quả mô hình. Thông tin chưa xác minh không phải số đo chính thức và không tự thay đổi dự báo hoặc lộ trình.</footer></div>`}
function build(){if(panel)return;if(standalone){panel=document.querySelector('[data-community-page]');panel.className='cg-panel cg-page';panel.innerHTML=layout()}else{panel=document.createElement('dialog');panel.className='cg-panel';panel.setAttribute('aria-labelledby','cgTitle');panel.innerHTML=layout();document.body.appendChild(panel);panel.addEventListener('close',()=>{requestId++;lastButton?.focus()})}bind()}
async function open(button){build();lastButton=button||lastButton;if(!standalone&&!panel.open)panel.showModal();message('Đang tải dữ liệu cộng đồng…');await refresh();setTimeout(()=>miniMap?.invalidateSize(),100)}
function mapInit(){if(miniMap||!window.L)return;miniMap=L.map(el('cgMap')).setView([10.78,106.69],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(miniMap);pins=L.layerGroup().addTo(miniMap);miniMap.on('click',event=>{if(!el('cgForm').hidden)setLocation(event.latlng.lat,event.latlng.lng)})}
function setLocation(lat,lon){chosen={lat,lon};el('cgLocation').textContent=`Đã chọn ${lat.toFixed(4)}, ${lon.toFixed(4)}`;if(miniMap){draftPin?.remove();draftPin=L.circleMarker([lat,lon],{radius:10,color:'#2478c6',fillColor:'#2478c6',fillOpacity:.35,weight:3}).addTo(miniMap).bindTooltip('Vị trí báo cáo');miniMap.setView([lat,lon],16)}submitMessage('Đã chọn vị trí. Kiểm tra địa điểm, ảnh rồi bấm Gửi báo cáo.')}
function gps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Thiết bị không hỗ trợ định vị.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(new Error('Chưa lấy được vị trí. Hãy cho phép định vị khi xác nhận báo cáo.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
function rewardMessage(text,error=false){const n=el('cgRewardStatus');if(n){n.textContent=text;n.classList.toggle('error',error)}}
function renderBadges(){const earned=Number(me.earned)||0,tiers=me.tiers||[],next=tiers.find(t=>!t.achieved);el('cgVoucherCount').textContent='Xem Điểm & quà';el('cgBadgeProgress').textContent=me.authenticated?(next?`${earned} điểm đóng góp · còn ${Math.max(0,next.threshold-earned)} điểm để đạt ${next.name}.`:'Bạn đã đạt tất cả các mốc huy hiệu.'):'Đăng nhập để theo dõi các mốc huy hiệu.';el('cgBadgeTiers').innerHTML=tiers.map((t,i)=>`<article class="cg-tier ${t.achieved?'achieved':''}"><span class="cg-tier-number">${i+1}</span><div><b>${esc(t.name)}</b><p>${Number(t.threshold)} điểm đóng góp</p><strong>Thưởng +${Number(t.bonus)} điểm</strong><small>${t.claimed?'Đã nhận thưởng':t.achieved?'Đã đạt mốc':'Chưa đạt mốc'}</small></div></article>`).join('')}
async function loadRewards(serial){const d=await api('rewards');if(serial!==requestId)return;el('cgVoucherCatalog').innerHTML=(d.vouchers||[]).map(v=>{const missing=Math.max(0,Number(v.cost)-Number(me.points));return `<article class="cg-voucher"><span class="cg-trial">THỬ NGHIỆM · KHÔNG CÓ GIÁ TRỊ ĐỐI TÁC</span><h4>${esc(v.title)}</h4><p>${esc(v.description)}</p><strong>${Number(v.cost)} điểm</strong><small>Hạn ${Number(v.validity_days)} ngày từ khi đổi</small><button type="button" class="cg-primary" data-redeem="${esc(v.sku)}" data-cost="${Number(v.cost)}" ${!me.authenticated||missing||redeemBusy?'disabled':''}>${!me.authenticated?'Đăng nhập để đổi':missing?'Còn thiếu '+missing+' điểm':'Đổi voucher'}</button></article>`}).join('');const mine=d.redemptions||[];el('cgVoucherCount').textContent=mine.length+' đã đổi';el('cgMyVouchers').innerHTML=mine.length?mine.map(v=>`<article class="cg-owned-voucher"><b>${esc(v.title)} · thử nghiệm</b><p>Đã đổi ${Number(v.cost)} điểm · ${new Date(v.created_at).toLocaleDateString('vi-VN')}</p><code>${esc(v.code)}</code><p>${new Date(v.expires_at)<=new Date()?'Đã hết hạn':'Hạn đến '+new Date(v.expires_at).toLocaleDateString('vi-VN')} · Không sử dụng tại đối tác.</p><button type="button" class="cg-secondary" data-copy="${esc(v.code)}">Sao chép mã</button></article>`).join(''):'<p>Bạn chưa đổi voucher nào.</p>'}
async function redeem(button){if(redeemBusy||!requireLogin())return;const sku=button.dataset.redeem,cost=Number(button.dataset.cost);if(!window.confirm(`Đổi voucher THỬ NGHIỆM với ${cost} điểm? Điểm sẽ bị trừ. Mã chưa sử dụng được tại đối tác.`))return;redeemBusy=true;panel.querySelectorAll('[data-redeem]').forEach(b=>b.disabled=true);rewardMessage('Đang đổi voucher…');try{let request=rewardRequest?.sku===sku?rewardRequest.request:null;try{request=sessionStorage.getItem('fg-redeem-'+sku)||request}catch{}if(!request)request=window.crypto.randomUUID();rewardRequest={sku,request};try{sessionStorage.setItem('fg-redeem-'+sku,request)}catch{}const result=await api('redeem',{method:'POST',body:JSON.stringify({sku,request_id:request})});try{sessionStorage.removeItem('fg-redeem-'+sku)}catch{}rewardRequest=null;redeemBusy=false;await refresh();rewardMessage(result.message+' Mã: '+result.voucher.code);}catch(e){rewardMessage(e.message+' Nếu yêu cầu bị gián đoạn, bấm đổi lại cùng voucher: hệ thống không trừ điểm lần nữa cho yêu cầu này.',true);}finally{redeemBusy=false;panel.querySelectorAll('[data-redeem]').forEach(b=>b.disabled=!me.authenticated||Number(b.dataset.cost)>Number(me.points));}}
function draw(){mapInit();pins?.clearLayers();reports.forEach(r=>{if(!pins)return;L.circleMarker([r.lat,r.lon],{radius:7,color:r.status==='verified'?'#20795d':'#c17b16',fillOpacity:.8}).addTo(pins).bindTooltip(esc(r.place))});el('cgCount').textContent=reports.length?`${reports.length} báo cáo`:'Chưa có báo cáo';el('cgList').innerHTML=reports.length?reports.map(r=>{
const closed=['expired','verified','rejected','resolved'].includes(r.status),when=new Date(r.created_at).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});
return `<article class="cg-report" data-report="${r.id}"><div class="cg-report-top"><span class="cg-status ${r.status}">${labels[r.status]||labels.pending}</span><time>${when}</time></div><h4>${esc(r.place)}</h4><p>${severity[r.severity]||''}</p>${r.description?`<p>${esc(r.description)}</p>`:''}<small>${r.confirmations} xác nhận · ${r.disagreements} ý kiến khác${r.mine?' · Báo cáo của bạn':''}</small>${r.review_note?`<p class="cg-small">Ghi chú duyệt: ${esc(r.review_note)}</p>`:''}<div class="cg-report-actions"><button data-map="${r.id}" type="button">Xem vị trí</button>${r.has_photo?`<button data-photo="${r.id}" type="button">Xem ảnh</button>`:''}${!closed&&!r.mine&&!r.voted?`<button data-confirm="${r.id}" data-agrees="true" type="button">Tôi thấy vẫn ngập</button><button data-confirm="${r.id}" data-agrees="false" type="button">Thông tin đã thay đổi</button>`:''}</div><div class="cg-photo-slot"></div></article>`}).join(''):`<div class="cg-empty"><h4>${mode==='mine'?'Bạn chưa có báo cáo':'Chưa có báo cáo trong mục này'}</h4><p>Bạn có thể đóng góp tình trạng đường khi quan sát được tại nơi an toàn.</p></div>`}
async function refresh(){const id=++requestId;try{const info=await api('me');if(id!==requestId)return;me=info;el('cgPoints').textContent=me.authenticated?me.points:'—';el('cgBadge').textContent=me.authenticated?me.badge:'Đăng nhập để xem';el('cgLogin').hidden=me.authenticated;renderBadges();el('cgHistory').innerHTML=me.history?.length?me.history.map(p=>`<p><b>${p.points>0?'+':''}${Number(p.points)}</b> · ${esc(({report:'Báo cáo được xác minh',confirmation:'Xác nhận hữu ích',milestone:'Thưởng mốc huy hiệu',redemption:'Đổi voucher'})[p.reason]||'Điểm đóng góp')} · ${new Date(p.created_at).toLocaleDateString('vi-VN')}</p>`).join(''):'<p>Chưa có điểm được ghi nhận.</p>';if(mode==='rewards'){await loadRewards(id);message('');return}if(mode==='mine'&&!me.authenticated){reports=[];draw();message('Đăng nhập để xem lịch sử đóng góp.');return}const d=await api('feed?mode='+mode);if(id!==requestId)return;reports=d.reports||[];draw();message('')}catch(e){if(id===requestId)message(e.message,true)}}
function bind(){panel.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){panel.close();return}if(b.dataset.mode){if(!['feed','mine','rewards'].includes(b.dataset.mode)||redeemBusy)return;mode=b.dataset.mode;panel.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));el('cgContent').hidden=mode==='rewards';el('cgRewards').hidden=mode!=='rewards';el('cgForm').hidden=true;await refresh();miniMap?.invalidateSize();return}if(b.dataset.map){const r=reports.find(x=>x.id===b.dataset.map);if(r)miniMap?.setView([r.lat,r.lon],16);el('cgMap').scrollIntoView({block:'center',behavior:'smooth'});return}if(b.dataset.photo){if(!requireLogin())return;b.disabled=true;try{const d=await api('photo/'+b.dataset.photo);b.closest('.cg-report').querySelector('.cg-photo-slot').innerHTML=`<img alt="Ảnh hiện trường của báo cáo" src="${d.photo}" class="cg-report-photo">`}catch(e){message(e.message,true)}finally{b.disabled=false}return}if(b.dataset.confirm){if(!requireLogin())return;b.disabled=true;try{message('Đang lấy vị trí để xác nhận…');const location=await gps();await api('confirm',{method:'POST',body:JSON.stringify({report_id:b.dataset.confirm,agrees:b.dataset.agrees==='true',...location})});await refresh();message('Đã ghi nhận. Điểm chỉ được cộng khi báo cáo được duyệt.')}catch(e){message(e.message,true)}finally{b.disabled=false}return}if(b.dataset.redeem){await redeem(b);return}if(b.dataset.copy){const code=b.dataset.copy;try{await navigator.clipboard.writeText(code);rewardMessage('Đã sao chép mã.')}catch{rewardMessage('Không sao chép tự động được. Hãy chọn và sao chép mã hiển thị.')}return}});
el('cgNew').onclick=()=>{if(!requireLogin())return;el('cgForm').hidden=false;el('cgForm').scrollIntoView({block:'start',behavior:'smooth'});miniMap?.invalidateSize()};el('cgCancel').onclick=()=>{el('cgForm').hidden=true};el('cgRefresh').onclick=refresh;
el('cgChooseMap').onclick=()=>{message('Chạm đúng vị trí báo cáo trên bản đồ.');el('cgMap').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});miniMap?.invalidateSize()};
el('cgLocate').onclick=async()=>{const b=el('cgLocate');b.disabled=true;try{const p=await gps();setLocation(p.lat,p.lon);message('Đã chọn vị trí hiện tại.')}catch(e){message(e.message,true)}finally{b.disabled=false}};
el('cgRemovePhoto').onclick=()=>{photoVersion++;photo=null;photoProcessing=false;photoError='';el('cgPhoto').value='';el('cgPreview').hidden=true;el('cgPreview').removeAttribute('src');el('cgRemovePhoto').hidden=true;el('cgPhotoStatus').textContent='Chọn ảnh từ thư viện hoặc máy ảnh.';el('cgSubmit').disabled=busy};
el('cgPhoto').onchange=async()=>{const version=++photoVersion,file=el('cgPhoto').files[0];photoProcessing=!!file;photoError='';photo=null;el('cgSubmit').disabled=photoProcessing||busy;el('cgPreview').hidden=true;el('cgRemovePhoto').hidden=!file;el('cgPhotoStatus').textContent=file?'Đang xử lý ảnh…':'Chưa chọn ảnh.';try{if(!window.FGReportPhoto)throw Error('Chưa tải được chức năng ảnh. Hãy tải lại trang.');const value=await window.FGReportPhoto.compress(file);if(version!==photoVersion)return;photo=value;if(value){el('cgPreview').src=value;el('cgPreview').hidden=false;el('cgPhotoStatus').textContent='Ảnh đã sẵn sàng. Bấm Gửi báo cáo để lưu cùng vị trí và mô tả.'}}catch(e){if(version!==photoVersion)return;photoError=e.message;el('cgPhotoStatus').textContent=e.message;message(e.message,true)}finally{if(version===photoVersion){photoProcessing=false;el('cgSubmit').disabled=busy}}};
el('cgForm').onsubmit=async event=>{
 event.preventDefault();if(busy)return;
 panel.querySelectorAll('[aria-invalid="true"]').forEach(n=>n.removeAttribute('aria-invalid'));
 const data={authenticated:me.authenticated,chosen,photoProcessing,photoError,place:el('cgPlace').value,description:el('cgDescription').value,severity:el('cgSeverity').value,consent:el('cgConsent').checked};
 const issue=window.FGReportValidation?window.FGReportValidation.validate(data):{message:'Chưa tải được chức năng gửi báo cáo. Hãy tải lại trang.',field:null};
 if(issue){if(issue.field)el(issue.field)?.setAttribute('aria-invalid','true');submitMessage(issue.message,true);el('cgSubmitStatus').scrollIntoView({block:'nearest',behavior:'auto'});return}
 busy=true;submitMessage('Đang gửi báo cáo và ảnh…');el('cgSubmit').disabled=true;el('cgSubmit').textContent='Đang gửi…';el('cgPhoto').disabled=true;el('cgRemovePhoto').disabled=true;
 try{
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);let d;
  try{d=await api('reports',{method:'POST',signal:controller.signal,body:JSON.stringify({...chosen,place:data.place.trim(),description:data.description.trim(),severity:data.severity,photo,share_consent:data.consent})})}finally{clearTimeout(timeout)}
  el('cgForm').reset();el('cgForm').hidden=true;photo=null;photoError='';photoVersion++;chosen=null;draftPin?.remove();draftPin=null;el('cgPreview').hidden=true;el('cgPreview').removeAttribute('src');el('cgRemovePhoto').hidden=true;el('cgPhotoStatus').textContent='Chọn ảnh từ thư viện hoặc máy ảnh.';el('cgLocation').textContent='Chưa chọn vị trí báo cáo.';submitMessage('');
  await refresh();message(d.message);el('cgMessage').scrollIntoView({block:'nearest',behavior:'auto'});
 }catch(e){submitMessage(e.name==='AbortError'||e.name==='TimeoutError'?'Máy chủ chưa phản hồi. Kiểm tra mục Của tôi trước khi gửi lại để tránh báo cáo trùng.':e.message||'Chưa gửi được báo cáo. Hãy thử lại.',true);el('cgSubmitStatus').scrollIntoView({block:'nearest',behavior:'auto'});
 }finally{busy=false;el('cgSubmit').disabled=false;el('cgSubmit').textContent='Gửi báo cáo';el('cgPhoto').disabled=false;el('cgRemovePhoto').disabled=false}
};
}
function entry(){const nav=document.querySelector('#fg3App .fg3-nav');if(nav&&!document.getElementById('fgCommunityBtn')){const b=document.createElement('button');b.id='fgCommunityBtn';b.className='fg3-btn hide-mobile';b.type='button';b.setAttribute('aria-label','Đóng góp cộng đồng');b.title='Đóng góp cộng đồng';b.innerHTML='<span class="fg14-nav-ico" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 4v2"/></svg></span><span class="fg14-nav-label">Cộng đồng</span>';b.onclick=()=>open(b);nav.appendChild(b)}const grid=document.querySelector('#fg14MoreSheet .fg14-more-grid');if(grid&&!grid.querySelector('[data-community-entry]')){const b=document.createElement('button');b.type='button';b.className='fg14-more-item';b.dataset.communityEntry='1';b.innerHTML='<strong>◎</strong><div><b>Đóng góp cộng đồng</b><span>Báo cáo ngập, điểm và voucher</span></div>';b.onclick=()=>{document.getElementById('fg14MoreSheet')?.classList.remove('show');document.getElementById('fg14MoreBack')?.classList.remove('show');open(b)};grid.appendChild(b)}}
if(standalone)open();else{entry();const observer=new MutationObserver(entry);observer.observe(document.body,{subtree:true,childList:true});setTimeout(()=>observer.disconnect(),30000)}
})();
