(()=>{'use strict';
const API='https://floodguard-rescue-backend.onrender.com',page=location.pathname.endsWith('about.html')?'about':location.pathname.endsWith('contact.html')?'contact':'home';
const preview=new URLSearchParams(location.search).get('editorPreview')==='1'&&parent!==window;
let schema,config={},originals=new Map(),logos=new Map(),editing=false;
const visibility=document.createElement('style');visibility.textContent='#fgAboutCustomImage[hidden],.about-chapter[hidden],.about-index a[hidden]{display:none!important}';document.head.appendChild(visibility);
const style=document.createElement('style');style.id='fg-published-theme';document.head.appendChild(style);
function safeImage(v){return typeof v==='string'&&(/^https:\/\//.test(v)||/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v))}
function apply(c){config=c||{};for(const f of schema.fields.filter(f=>f.page===page)){const n=document.querySelector(f.selector);if(!n)continue;if(!originals.has(f.key))originals.set(f.key,n.innerHTML);if(typeof config.fields?.[f.key]==='string')n.textContent=config.fields[f.key];else n.innerHTML=originals.get(f.key);}
 if(page==='contact'){window.FGContactEmail=config.fields?.['contact.email']||'mas24080419@hsb.edu.vn';document.querySelectorAll('.fg-contact-email a[href^="mailto:"]').forEach(a=>a.href='mailto:'+window.FGContactEmail+(a.classList.contains('fg-contact-address')?'':'?subject='+encodeURIComponent('Phản hồi FloodGuard')))}
 const t=config.theme;if(t&&/^#[0-9a-f]{6}$/i.test(t.accent)){const scale=Math.min(1.2,Math.max(.9,Number(t.fontScale)||1)),spacing=Math.min(1.3,Math.max(.8,Number(t.spacing)||1)),radius=Math.min(32,Math.max(8,Number(t.radius)||20));style.textContent=`html:root{--fg-blue:${t.accent};--blue:${t.accent}}html:root body .site-btn.primary,html:root body .wh-btn.primary,html:root body .fg-contact-button{background:${t.accent}!important;color:white!important;border-color:${t.accent}!important}html:root body main p,html:root body .website-home p{font-size:${Math.round(16*scale)}px!important;line-height:1.75!important}html:root body .about-chapter,html:root body .fg-contact-card,html:root body .wh-card{border-radius:${radius}px!important}html:root body .about-chapter{padding-top:${Math.round(28*spacing)}px!important;padding-bottom:${Math.round(28*spacing)}px!important}html:root body .fg-contact-grid{gap:${Math.round(18*spacing)}px!important}`;}else style.textContent='';
 document.querySelectorAll('.site-logo,.wh-logo').forEach(n=>{if(!logos.has(n))logos.set(n,n.innerHTML);const src=config.assets?.logo;if(src&&safeImage(src)){const img=document.createElement('img');img.src=src;img.alt='FloodGuard';img.onerror=()=>{n.innerHTML=logos.get(n)};img.style.cssText='width:100%;height:100%;object-fit:contain;border-radius:inherit';n.replaceChildren(img)}else n.innerHTML=logos.get(n)});
 if(page==='about'){for(const i of[1,2,3,4]){const n=document.querySelector('#chapter-'+i),link=document.querySelector('.about-index a[href="#chapter-'+i+'"]');const hidden=(config.hidden||[]).includes(i);if(n)n.hidden=hidden;if(link)link.hidden=hidden}for(const i of config.order||[1,2,3,4]){const n=document.querySelector('#chapter-'+i),a=document.querySelector('.about-index a[href="#chapter-'+i+'"]');if(n)n.parentElement.appendChild(n);if(a)a.parentElement.appendChild(a)}let img=document.getElementById('fgAboutCustomImage');if(!img){img=document.createElement('img');img.id='fgAboutCustomImage';img.alt='Hình giới thiệu FloodGuard';img.style.cssText='display:block;width:100%;max-height:360px;object-fit:cover;border-radius:20px;margin:0 0 24px';document.querySelector('.about-story > div')?.prepend(img)}const src=config.assets?.about;img.hidden=!(src&&safeImage(src));if(!img.hidden)img.src=src;else img.removeAttribute('src')}
 if(preview&&!editing)enable();}
function send(type,data){parent.postMessage({type,...data},location.origin)}
function enable(){editing=true;const s=document.createElement('style');s.textContent='[data-fg-edit-key]{outline:1px dashed #6d9dd7;outline-offset:5px;cursor:text}[data-fg-edit-key]:focus{outline:3px solid #357ec7}[hidden]{display:none!important}';document.head.appendChild(s);for(const f of schema.fields.filter(f=>f.page===page)){const n=document.querySelector(f.selector);if(!n)continue;n.dataset.fgEditKey=f.key;n.contentEditable='plaintext-only';n.addEventListener('focus',()=>send('fg-editor-select',{key:f.key}));n.addEventListener('input',()=>send('fg-editor-input',{key:f.key,value:n.textContent.slice(0,f.max)}));n.addEventListener('paste',e=>{e.preventDefault();document.execCommand('insertText',false,(e.clipboardData.getData('text/plain')||'').slice(0,f.max))})}document.addEventListener('click',e=>{if(e.target.closest('a,button')&&!e.target.closest('[data-fg-edit-key]')){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation()},true);}
async function init(){schema=await fetch('./site-editor-fields.json?v=1').then(r=>r.json());if(preview){const defaults={};for(const f of schema.fields.filter(f=>f.page===page)){const n=document.querySelector(f.selector);if(n)defaults[f.key]=n.textContent.trim()}window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='fg-editor-apply')return;apply(e.data.content)});send('fg-editor-ready',{defaults,page});return}try{const r=await fetch(API+'/api/site-content',{cache:'no-store',signal:AbortSignal.timeout(7000)});if(r.ok)apply((await r.json()).content)}catch{} }
init().catch(()=>{});
})();
