(()=>{'use strict';const API='https://floodguard-rescue-backend.onrender.com',$=id=>document.getElementById(id);
let sb,schema,state,content,defaults={},dirty=false,busy=false,ready=false,pending,selectedField,selectedBlock;
const normalize=c=>({fields:{...c?.fields},theme:{accent:'#357ec7',fontScale:1,spacing:1,radius:20,...c?.theme},assets:{logo:'',about:'',...c?.assets},hidden:[...(c?.hidden||[])],order:[...(c?.order||[1,2,3,4])],styles:structuredClone(c?.styles||{}),orders:structuredClone(c?.orders||{})});
function status(text,error=false){$('status').textContent=text;$('status').style.color=error?'#ffbdbd':''}
function controls(){$('workspace').inert=busy;for(const id of['save','publish','reload','restore'])$(id).disabled=busy||!state||(id==='restore'&&!state.has_previous);$('draftBadge').textContent=dirty?'Có thay đổi chưa lưu':'Bản nháp · chưa xuất bản';$('versionInfo').textContent=state?'Phiên bản '+state.revision+' · '+(state.published_at?'Xuất bản '+new Date(state.published_at).toLocaleString('vi-VN'):'Chưa xuất bản từ trình chỉnh sửa'):''}
function changed(preview=true){dirty=true;controls();if(preview)apply()}
function apply(){if(ready)$('preview').contentWindow.postMessage({type:'fg-editor-apply',content},location.origin)}
function focus(key){if(ready)$('preview').contentWindow.postMessage({type:'fg-editor-focus',key},location.origin)}
async function api(method='GET',body){const {data}=await sb.auth.getSession();if(!data.session)throw Error('Hãy đăng nhập bằng tài khoản admin.');const r=await fetch(API+'/api/admin/site-editor',{method,headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw Error(d.message||'Không thực hiện được yêu cầu.');return d}
function theme(){for(const id of['accent','fontScale','spacing','radius'])$(id).value=content.theme[id];$('fontValue').textContent=Math.round(content.theme.fontScale*100)+'%';$('spaceValue').textContent=Math.round(content.theme.spacing*100)+'%';$('radiusValue').textContent=content.theme.radius+' px';for(const id of['logo','about'])$(id+'Url').value=content.assets[id].startsWith('data:')?'':content.assets[id]}
function list(){const q=$('searchFields').value.trim().toLocaleLowerCase('vi'),current=$('page').value,items=schema.fields.filter(f=>f.page===current&&(!q||(f.label+' '+f.key+' '+f.group+' '+(content.fields[f.key]||'')).toLocaleLowerCase('vi').includes(q)));$('fieldCount').textContent=items.length+' mục nội dung trên trang này';const select=$('fieldList');select.replaceChildren();for(const f of items){const o=document.createElement('option');o.value=f.key;o.textContent=({image:'Ảnh · ',link:'Liên kết · ',placeholder:'Ô nhập · '}[f.type]||'')+f.label;select.append(o)}if(items.some(f=>f.key===selectedField?.key))select.value=selectedField.key;else selectedField=items[0]||null;if(selectedField){select.value=selectedField.key;field(false)}else $('fieldDetail').hidden=true}
function field(scroll=true){selectedField=schema.fields.find(f=>f.key===$('fieldList').value);$('fieldDetail').hidden=!selectedField;if(!selectedField)return;const f=selectedField;$('fieldLabel').textContent=f.label;const value=content.fields[f.key]??defaults[f.key]??f.default??'';$('fieldValue').value=f.type==='image'&&value.startsWith('data:')?'':value;$('fieldValue').maxLength=f.max;$('fieldImageTools').hidden=f.type!=='image';$('fieldHint').textContent=f.type==='image'?'Dán URL ảnh HTTPS hoặc chọn ảnh.':f.type==='link'?'Dùng HTTPS, mailto:, tel:, # hoặc đường dẫn trong website.':f.type==='placeholder'?'Chỉ thay chữ gợi ý, không thay giá trị người dùng nhập.':'Nội dung hiển thị; không chèn mã HTML.';const b=schema.blocks.find(b=>b.page===f.page&&b.selector===f.selector);if(b){$('element').value=b.key;block(false)}if(scroll)focus(f.key)}
function block(scroll=true){selectedBlock=schema.blocks.find(b=>b.key===$('element').value);$('elementSettings').hidden=!selectedBlock;if(!selectedBlock)return;const settings=content.styles[selectedBlock.key]||{};$('elementName').textContent=selectedBlock.label;for(const name of['color','background','fontSize','padding','radius','gap','width','maxWidth','align'])$('node-'+name).value=settings[name]??'';$('node-hidden').checked=!!settings.hidden;if(scroll)focus(selectedBlock.key)}
function blockList(){const select=$('element');select.replaceChildren();for(const b of schema.blocks.filter(b=>b.page===$('page').value)){const o=document.createElement('option');o.value=b.key;o.textContent=b.tag+' · '+b.label;select.append(o)}if(selectedBlock?.page===$('page').value)select.value=selectedBlock.key;block(false)}
function fields(){list();blockList();chapters()}
function chapters(){$('chapters').hidden=$('page').value!=='about';const box=$('chapterList');box.replaceChildren();content.order.forEach((n,i)=>{const row=document.createElement('div');row.className='ed-chapter';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=!content.hidden.includes(n);check.onchange=()=>{content.hidden=check.checked?content.hidden.filter(x=>x!==n):[...content.hidden,n];changed()};label.append(check,document.createTextNode(' Phần '+n));row.append(label);for(const [delta,text]of[[-1,'↑'],[1,'↓']]){const b=document.createElement('button');b.textContent=text;b.disabled=i+delta<0||i+delta>3;b.onclick=()=>{[content.order[i],content.order[i+delta]]=[content.order[i+delta],content.order[i]];chapters();changed()};row.append(b)}box.append(row)})}
function page(){ready=false;defaults={};selectedField=null;selectedBlock=null;$('searchFields').value='';fields();const p=schema.pages.find(p=>p.id===$('page').value);$('openPublic').href='./'+p.file+(p.id==='home'?'?home=1':p.id==='login'?'?login=1':'');$('preview').src='./editor-preview/'+p.id+'.html?editorPreview=1'}
async function load(){if(dirty&&!confirm('Tải bản mới sẽ bỏ các thay đổi chưa lưu. Tiếp tục?'))return;busy=true;controls();try{state=await api();content=normalize(state.draft);dirty=false;theme();fields();apply();status('Đã tải bản nháp mới nhất.')}catch(e){status(e.message,true)}finally{busy=false;controls()}}
async function write(action){if(busy)return;busy=true;controls();try{state=await api('POST',{action,revision:state.revision,content});content=normalize(state.draft);dirty=false;theme();fields();if(action==='restore')page();else apply();status(state.message)}catch(e){status(e.message,true)}finally{busy=false;controls()}}
function ask(action){pending=action;$('confirmTitle').textContent=action==='publish'?'Xuất bản thay đổi toàn website?':'Khôi phục bản trước?';$('confirmMessage').textContent=action==='publish'?'Tất cả thay đổi trong bản nháp, trên mọi trang, sẽ hiển thị khi người dùng tải lại website.':'Website và bản nháp sẽ trở về bản đã xuất bản trước đó.';$('publishConfirm').showModal()}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('preview').contentWindow)return;const d=e.data;if(d?.type==='fg-editor-ready'&&d.page===$('page').value){defaults=d.defaults||{};ready=true;fields();apply()}else if(d?.type==='fg-editor-input'){const f=schema.fields.find(f=>f.key===d.key&&f.page===$('page').value);if(!f||typeof d.value!=='string')return;content.fields[f.key]=d.value.slice(0,f.max);if(selectedField?.key===f.key)$('fieldValue').value=content.fields[f.key];changed(false)}else if(d?.type==='fg-editor-select'){const f=schema.fields.find(f=>f.key===d.key&&f.page===$('page').value);if(f){selectedField=f;$('searchFields').value='';list();$('fieldList').value=f.key;field(false)}else if(schema.blocks.some(b=>b.key===d.key&&b.page===$('page').value)){$('element').value=d.key;block(false)}}});
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Chọn ảnh JPG, PNG hoặc WebP dưới 15 MB.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),ratio=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let v=canvas.toDataURL('image/webp',.82);if(v.length>300000)v=canvas.toDataURL('image/webp',.5);if(v.length>300000)throw Error('Ảnh còn quá lớn. Chọn ảnh nhỏ hơn.');return v}
$('searchFields').oninput=list;$('fieldList').onchange=()=>field();$('element').onchange=()=>block();$('fieldValue').oninput=()=>{if(!selectedField)return;content.fields[selectedField.key]=$('fieldValue').value;changed()};$('resetField').onclick=()=>{if(!selectedField)return;delete content.fields[selectedField.key];field(false);changed()};$('fieldImage').onchange=async()=>{const f=$('fieldImage').files[0],key=selectedField?.key;if(!f||!key)return;try{content.fields[key]=await compress(f);if(selectedField?.key===key)field(false);changed();status('Đã thêm ảnh vào bản nháp.')}catch(e){status(e.message,true)}finally{$('fieldImage').value=''}};
for(const name of['color','background','fontSize','padding','radius','gap','width','maxWidth','align'])$('node-'+name).onchange=()=>{if(!selectedBlock)return;const settings=content.styles[selectedBlock.key]||{},v=$('node-'+name).value;if(!v)delete settings[name];else if(['color','background'].includes(name)){if(!/^#[0-9a-f]{6}$/i.test(v))return status('Nhập mã màu như #357ec7.',true);settings[name]=v}else settings[name]=name==='align'?v:Number(v);content.styles[selectedBlock.key]=settings;changed()};$('node-hidden').onchange=()=>{if(selectedBlock){content.styles[selectedBlock.key]={...content.styles[selectedBlock.key],hidden:$('node-hidden').checked};changed()}};$('resetElement').onclick=()=>{if(selectedBlock){delete content.styles[selectedBlock.key];block(false);changed()}};
function move(delta){if(!selectedBlock)return;const p=$('page').value,blocks=schema.blocks.filter(b=>b.page===p),order=[...(content.orders[p]||blocks.map(b=>b.key))],siblings=order.filter(k=>schema.blocks.find(b=>b.key===k)?.parent===selectedBlock.parent),i=siblings.indexOf(selectedBlock.key),other=siblings[i+delta];if(!other)return status('Thành phần đã ở đầu hoặc cuối nhóm.');const a=order.indexOf(selectedBlock.key),b=order.indexOf(other);[order[a],order[b]]=[order[b],order[a]];content.orders[p]=order;changed();status('Đã đổi vị trí trong cùng nhóm bố cục.')}$('moveUp').onclick=()=>move(-1);$('moveDown').onclick=()=>move(1);$('resetOrder').onclick=()=>{delete content.orders[$('page').value];changed();page()};
for(const id of['accent','fontScale','spacing','radius'])$(id).oninput=()=>{content.theme[id]=id==='accent'?$(id).value:Number($(id).value);theme();changed()};for(const id of['logo','about']){$(id+'Url').onchange=()=>{const v=$(id+'Url').value.trim();if(v&&!/^https:\/\//.test(v))return status('Dùng đường dẫn ảnh HTTPS.',true);content.assets[id]=v;changed()};$('clear'+(id==='logo'?'Logo':'About')).onclick=()=>{content.assets[id]='';theme();changed()};$(id+'File').onchange=async()=>{const f=$(id+'File').files[0];if(!f)return;try{content.assets[id]=await compress(f);theme();changed()}catch(e){status(e.message,true)}finally{$(id+'File').value=''}}}
$('page').onchange=page;$('save').onclick=()=>write('save');$('publish').onclick=()=>ask('publish');$('restore').onclick=()=>ask('restore');$('reload').onclick=load;$('cancelConfirm').onclick=()=>$('publishConfirm').close();$('acceptConfirm').onclick=()=>{$('publishConfirm').close();write(pending)};for(const mode of['desktop','mobile'])$(mode).onclick=()=>{$('preview').classList.toggle('mobile',mode==='mobile');$(mode).classList.add('active');$(mode==='mobile'?'desktop':'mobile').classList.remove('active')};for(const tab of['content','theme'])$(tab+'Tab').onclick=()=>{for(const x of['content','theme']){$(x+'Fields').hidden=x!==tab;$(x+'Tab').classList.toggle('active',x===tab)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{schema=await fetch('./site-editor-fields.json?v=2').then(r=>r.json());const select=$('page');select.replaceChildren();for(const group of['Công khai','Ứng dụng','Quản trị']){const g=document.createElement('optgroup');g.label=group;for(const p of schema.pages.filter(p=>p.group===group)){const o=document.createElement('option');o.value=p.id;o.textContent=p.label;g.append(o)}select.append(g)}const r=await fetch(API+'/api/public-config',{signal:AbortSignal.timeout(20000)}),d=await r.json();if(!r.ok||!d.supabase?.url||!window.supabase)throw Error('Không kết nối được dịch vụ đăng nhập.');sb=window.supabase.createClient(d.supabase.url,d.supabase.anon_key);state=await api();content=normalize(state.draft);$('auth').hidden=true;$('workspace').hidden=false;theme();controls();page()}catch(e){$('auth').querySelector('h1').textContent='Chưa mở được trình chỉnh sửa';$('authMessage').textContent=e.message}})();
})();
