(()=>{'use strict';
const API='https://floodguard-rescue-backend.onrender.com',$=id=>document.getElementById(id),paths={home:'./?home=1',about:'./about.html',contact:'./contact.html'};
let sb,schema,state,content,defaults={},dirty=false,busy=false,ready=false,pending;
const normalize=c=>({fields:{...c?.fields},theme:{accent:'#357ec7',fontScale:1,spacing:1,radius:20,...c?.theme},assets:{logo:'',about:'',...c?.assets},hidden:[...(c?.hidden||[])],order:[...(c?.order||[1,2,3,4])]});
function status(message,error=false){$('status').textContent=message;$('status').style.color=error?'#a52727':''}
function controls(){$('workspace').inert=busy;for(const id of['save','publish','reload','restore'])$(id).disabled=busy||!state||(id==='restore'&&!state.has_previous);$('draftBadge').textContent=dirty?'Có thay đổi chưa lưu':'Bản nháp · xem trước';$('versionInfo').textContent=state?'Phiên bản '+state.revision+' · '+(state.published_at?'Xuất bản '+new Date(state.published_at).toLocaleString('vi-VN'):'Chưa xuất bản từ trình chỉnh sửa'):''}
function changed(preview=true){dirty=true;controls();if(preview)apply()}
function apply(){if(ready)$('preview').contentWindow.postMessage({type:'fg-editor-apply',content},location.origin)}
async function api(method='GET',body){const {data}=await sb.auth.getSession();if(!data.session)throw Error('Phiên đăng nhập hết hạn. Hãy đăng nhập lại.');const r=await fetch(API+'/api/admin/site-editor',{method,headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw Error(d.message||'Không thực hiện được yêu cầu.');return d}
function theme(){for(const id of['accent','fontScale','spacing','radius'])$(id).value=content.theme[id];$('fontValue').textContent=Math.round(content.theme.fontScale*100)+'%';$('spaceValue').textContent=Math.round(content.theme.spacing*100)+'%';$('radiusValue').textContent=content.theme.radius+' px';for(const id of['logo','about'])$(id+'Url').value=content.assets[id].startsWith('data:')?'':content.assets[id]}
function fields(){const box=$('contentFields');box.replaceChildren();for(const f of schema.fields.filter(f=>f.page===$('page').value)){const label=document.createElement('label');label.className='ed-field';label.textContent=f.label;const input=document.createElement(f.type==='email'?'input':'textarea');input.id='field-'+f.key;input.maxLength=f.max;if(f.type==='email')input.type='email';input.value=content.fields[f.key]??defaults[f.key]??'';input.addEventListener('input',()=>{content.fields[f.key]=input.value;changed()});label.append(input);box.append(label)}chapters()}
function chapters(){$('chapters').hidden=$('page').value!=='about';const list=$('chapterList');list.replaceChildren();content.order.forEach((n,i)=>{const row=document.createElement('div');row.className='ed-chapter';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=!content.hidden.includes(n);check.onchange=()=>{content.hidden=check.checked?content.hidden.filter(x=>x!==n):[...content.hidden,n];changed()};label.append(check,document.createTextNode(' Phần '+n));row.append(label);for(const [offset,text]of[[-1,'↑'],[1,'↓']]){const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',(offset<0?'Đưa lên':'Đưa xuống')+' phần '+n);b.disabled=i+offset<0||i+offset>=4;b.onclick=()=>{[content.order[i],content.order[i+offset]]=[content.order[i+offset],content.order[i]];chapters();changed()};row.append(b)}list.append(row)})}
function page(){ready=false;defaults={};fields();$('openPublic').href=paths[$('page').value];$('preview').src=paths[$('page').value]+(paths[$('page').value].includes('?')?'&':'?')+'editorPreview=1'}
async function load(){if(dirty&&!confirm('Tải bản mới sẽ bỏ các thay đổi chưa lưu. Tiếp tục?'))return;busy=true;controls();try{state=await api();content=normalize(state.draft);dirty=false;theme();fields();apply();status('Đã tải bản nháp mới nhất.')}catch(e){status(e.message,true)}finally{busy=false;controls()}}
async function write(action){if(busy)return;busy=true;controls();try{const s=await api('POST',{action,revision:state.revision,content});state=s;content=normalize(s.draft);dirty=false;theme();fields();apply();status(s.message)}catch(e){status(e.message,true)}finally{busy=false;controls()}}
function ask(action){pending=action;$('confirmTitle').textContent=action==='publish'?'Xuất bản thay đổi?':'Khôi phục bản trước?';$('confirmMessage').textContent=action==='publish'?'Nội dung đang xem trước sẽ hiển thị trên website công khai sau khi tải lại trang.':'Website công khai và bản nháp sẽ trở về bản đã xuất bản trước đó.';$('publishConfirm').showModal()}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('preview').contentWindow)return;const d=e.data;if(d?.type==='fg-editor-ready'&&d.page===$('page').value){defaults=d.defaults||{};ready=true;fields();apply()}else if(d?.type==='fg-editor-input'){const f=schema.fields.find(f=>f.key===d.key&&f.page===$('page').value);if(!f||typeof d.value!=='string')return;content.fields[d.key]=d.value.slice(0,f.max);const input=$('field-'+d.key);if(input)input.value=content.fields[d.key];changed(false)}else if(d?.type==='fg-editor-select'){$('field-'+d.key)?.scrollIntoView({block:'nearest',behavior:'smooth'})}});
for(const id of['accent','fontScale','spacing','radius'])$(id).oninput=()=>{content.theme[id]=id==='accent'?$(id).value:Number($(id).value);theme();changed()};
for(const id of['logo','about']){$(id+'Url').onchange=()=>{const value=$(id+'Url').value.trim();try{if(value&&new URL(value).protocol!=='https:')throw Error();content.assets[id]=value;changed()}catch{status('Hãy dùng đường dẫn ảnh HTTPS.',true)}};$('clear'+(id==='logo'?'Logo':'About')).onclick=()=>{content.assets[id]='';theme();changed()};$(id+'File').onchange=async()=>{const file=$(id+'File').files[0];if(!file)return;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Chọn ảnh JPG, PNG hoặc WebP dưới 15 MB.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),ratio=Math.min(1,(id==='logo'?400:1400)/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let image=canvas.toDataURL('image/webp',.82);if(image.length>300000)image=canvas.toDataURL('image/webp',.55);if(image.length>300000)throw Error('Ảnh còn quá lớn. Hãy chọn ảnh nhỏ hơn.');content.assets[id]=image;theme();changed();status('Ảnh đã được thêm vào bản xem trước.')}catch(e){status(e.message,true)}finally{$(id+'File').value=''}}}
$('page').onchange=page;$('save').onclick=()=>write('save');$('publish').onclick=()=>ask('publish');$('restore').onclick=()=>ask('restore');$('reload').onclick=load;$('cancelConfirm').onclick=()=>$('publishConfirm').close();$('acceptConfirm').onclick=()=>{$('publishConfirm').close();write(pending)};
for(const mode of['desktop','mobile'])$(mode).onclick=()=>{$('preview').classList.toggle('mobile',mode==='mobile');$(mode).classList.add('active');$(mode==='mobile'?'desktop':'mobile').classList.remove('active')};
for(const tab of['content','theme'])$(tab+'Tab').onclick=()=>{for(const x of['content','theme']){$(x+'Fields').hidden=x!==tab;$(x+'Tab').classList.toggle('active',x===tab)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{schema=await fetch('./site-editor-fields.json?v=1').then(r=>r.json());const r=await fetch(API+'/api/public-config',{signal:AbortSignal.timeout(20000)}),d=await r.json();if(!r.ok||!d.supabase?.url||!window.supabase)throw Error('Không kết nối được dịch vụ đăng nhập.');sb=window.supabase.createClient(d.supabase.url,d.supabase.anon_key);state=await api();content=normalize(state.draft);$('auth').hidden=true;$('workspace').hidden=false;theme();controls();page()}catch(e){$('auth').querySelector('h1').textContent='Chưa mở được trình chỉnh sửa';$('authMessage').textContent=e.message}})();
})();
