(()=>{'use strict';
const API='https://floodguard-rescue-backend.onrender.com',preview=new URLSearchParams(location.search).get('editorPreview')==='1'&&parent!==window;
let schema,page,config={},observer,timer;const bound=new Map();function node(item){const old=bound.get(item.key);if(old?.isConnected)return old;const n=document.querySelector(item.selector);if(n)bound.set(item.key,n);return n}
const originals=new Map(),logoOriginals=new WeakMap(),customLogos=new WeakSet();
const theme=document.createElement('style'),specific=document.createElement('style');document.head.append(theme,specific);const visibility=document.createElement('style');visibility.textContent='.about-chapter[hidden],.about-index a[hidden]{display:none!important}';document.head.append(visibility);
const image=v=>typeof v==='string'&&(/^https:\/\//.test(v)||/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v));
const send=(type,data)=>parent.postMessage({type,...data},location.origin);
function applicable(p){return p===page||(page==='home'&&p==='login')||(page==='app'&&p==='community')}
function value(f,n){if(f.type==='placeholder')return n.getAttribute('placeholder')||'';if(f.type==='link')return n.getAttribute('href')||'';if(f.type==='image')return n.getAttribute('src')||'';if(Number.isInteger(f.textIndex))return n.childNodes[f.textIndex]?.nodeValue||'';return n.textContent}
function put(f,n,v){if(value(f,n)===v)return;if(f.type==='placeholder')n.setAttribute('placeholder',v);else if(f.type==='link')n.setAttribute('href',v);else if(f.type==='image'){if(v&&(image(v)||v.startsWith('./')||v.startsWith('../')||(v.startsWith('/')&&!v.startsWith('//'))||v===originals.get(f.key)?.value))n.setAttribute('src',v)}else if(Number.isInteger(f.textIndex)){const t=n.childNodes[f.textIndex];if(t?.nodeType===3){const original=originals.get(f.key)?.value||'';t.nodeValue=(original.match(/^\s*/)?.[0]||'')+v.trim()+(original.match(/\s*$/)?.[0]||'')}}else n.textContent=v}
function apply(c){config=c||{};const active=new Set([...Object.keys(config.fields||{}),...originals.keys()]);for(const key of active){const f=schema.byKey.get(key);if(!f||!applicable(f.page))continue;const n=node(f);if(!n)continue;if(!originals.has(key))originals.set(key,{node:n,value:value(f,n),html:n.innerHTML});const old=originals.get(key);if(old.node!==n)originals.set(key,{node:n,value:value(f,n),html:n.innerHTML});if(typeof config.fields?.[key]==='string')put(f,n,config.fields[key]);else if(!Number.isInteger(f.textIndex)&&['text','email'].includes(f.type)){if(n.innerHTML!==originals.get(key).html)n.innerHTML=originals.get(key).html;}else put(f,n,originals.get(key).value)}
 const t=config.theme;theme.textContent=t?`html:root{--fg-blue:${t.accent};--blue:${t.accent}}body .site-btn.primary,body .wh-btn.primary,body .fg-contact-button,body .cg-primary,body .gift-button{background:${t.accent}!important;border-color:${t.accent}!important}body main p,body .website-home p{font-size:${Math.round(16*t.fontScale)}px!important;line-height:1.75!important}body .about-chapter,body .fg-contact-card,body .wh-card,body .cg-form,body .gift-card{border-radius:${t.radius}px!important}body .page-section{padding-block:${Math.round(64*t.spacing)}px!important}body .fg-contact-grid{gap:${Math.round(18*t.spacing)}px!important}`:'';
 let css='';for(const [key,s]of Object.entries(config.styles||{})){const b=schema.blockKeys.get(key);if(!b||!applicable(b.page))continue;const rules=[];for(const [k,v]of Object.entries(s)){const names={color:'color',background:'background-color',fontSize:'font-size',padding:'padding',radius:'border-radius',gap:'gap',align:'text-align',width:'width',maxWidth:'max-width'};if(k==='hidden'){if(v)rules.push('display:none!important');continue}if(names[k])rules.push(names[k]+':'+(typeof v==='number'?v+'px':v)+'!important')}const n=node(b);if(n){n.dataset.fgStyleKey=key;if(preview&&s.hidden)n.style.removeProperty('display')}css+='[data-fg-style-key=\"'+key+'\"]{'+rules.join(';')+'}\n'}specific.textContent=css;
 document.querySelectorAll('.site-logo,.wh-logo,.fg3-logo,.cc-logo,.topbar .logo,.side .logo').forEach(n=>{if(!logoOriginals.has(n))logoOriginals.set(n,n.innerHTML);const src=config.assets?.logo;if(src&&image(src)){if(n.querySelector('img')?.getAttribute('src')===src)return;const img=document.createElement('img');img.src=src;img.alt='FloodGuard';img.style.cssText='width:100%;height:100%;object-fit:contain';img.onerror=()=>n.innerHTML=logoOriginals.get(n);n.replaceChildren(img);customLogos.add(n)}else if(customLogos.has(n)){n.innerHTML=logoOriginals.get(n);customLogos.delete(n)}});
 if(page==='contact'){window.FGContactEmail=config.fields?.['contact.email']||'mas24080419@hsb.edu.vn';document.querySelectorAll('.fg-contact-email a[href^="mailto:"]').forEach(n=>{const override=schema.fields.find(f=>f.page==='contact'&&f.type==='link'&&config.fields?.[f.key]&&node(f)===n);if(!override)n.href='mailto:'+window.FGContactEmail})}
 if(page==='about'){for(const i of[1,2,3,4]){const n=document.getElementById('chapter-'+i),a=document.querySelector('.about-index a[href="#chapter-'+i+'"]');if(n)n.hidden=(config.hidden||[]).includes(i);if(a){a.hidden=(config.hidden||[]).includes(i);if(!a.dataset.fgOriginalLabel)a.dataset.fgOriginalLabel=a.textContent;const label=config.fields?.['about.chapter'+i+'.title']?String(i).padStart(2,'0')+' · '+config.fields['about.chapter'+i+'.title']:a.dataset.fgOriginalLabel;if(a.textContent!==label)a.textContent=label}}if(!config.orders?.about){for(const kind of ['chapter','link']){const nodes=(config.order||[1,2,3,4]).map(i=>kind==='chapter'?document.getElementById('chapter-'+i):document.querySelector('.about-index a[href="#chapter-'+i+'"]')).filter(Boolean),p=nodes[0]?.parentElement;if(p){const current=[...p.children].filter(n=>nodes.includes(n));if(!current.every((n,i)=>n===nodes[i]))nodes.forEach(n=>p.append(n))}}}let img=document.getElementById('fgAboutCustomImage');const src=config.assets?.about;if(src&&image(src)){if(!img){img=document.createElement('img');img.id='fgAboutCustomImage';img.alt='Giới thiệu FloodGuard';img.style.cssText='display:block;width:100%;max-height:360px;object-fit:cover;border-radius:20px;margin-bottom:24px';document.querySelector('.about-story > div')?.prepend(img)}img.src=src}else img?.remove()}
 if(config.orders?.[page]){const grouped=new Map();for(const key of config.orders[page]){const b=schema.blockKeys.get(key),n=b?.page===page&&node(b);if(!n?.parentElement)continue;const list=grouped.get(n.parentElement)||[];if(!list.includes(n))list.push(n);grouped.set(n.parentElement,list)}for(const [parent,nodes]of grouped){if(nodes.length<2)continue;const natural=[...parent.children].filter(n=>nodes.includes(n));if(natural.every((n,i)=>n===nodes[i]))continue;const markers=natural.map(n=>{const marker=document.createComment('fg-order');n.before(marker);return marker});nodes.forEach((n,i)=>markers[i].replaceWith(n))}}
 window.dispatchEvent(new Event('fg-site-content-updated'));if(preview)enable();}
function reveal(n){for(let a=n;a&&a!==document.body;a=a.parentElement){a.hidden=false;a.classList.remove('hidden');if(a.tagName==='DIALOG')a.open=true;if(getComputedStyle(a).display==='none')a.style.setProperty('display','block','important');if(a.getAttribute('aria-hidden')==='true')a.setAttribute('aria-hidden','false');if(/panel|modal|backdrop|sheet|overlay/.test(a.className)&&getComputedStyle(a).position==='fixed'){a.style.setProperty('position','relative','important');a.style.setProperty('transform','none','important');a.style.setProperty('inset','auto','important');a.style.setProperty('opacity','1','important');a.style.setProperty('visibility','visible','important')}}n.scrollIntoView({block:'center',behavior:'smooth'});document.querySelectorAll('.fg-editor-selected').forEach(x=>x.classList.remove('fg-editor-selected'));n.classList.add('fg-editor-selected')}
function enable(){for(const f of schema.fields.filter(f=>applicable(f.page))){const n=node(f);if(!n||n.dataset.fgFieldKey)continue;n.dataset.fgFieldKey=f.key;const editable=['text','email'].includes(f.type)&&(!Number.isInteger(f.textIndex)||n.childNodes.length===1)&&!['OPTION','SELECT'].includes(n.tagName);if(editable){n.contentEditable='plaintext-only';n.addEventListener('input',()=>send('fg-editor-input',{key:f.key,value:value(f,n).slice(0,f.max)}));n.addEventListener('paste',e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain').slice(0,f.max))})}}
 for(const b of schema.blocks.filter(b=>applicable(b.page))){const n=node(b);if(n&&!n.dataset.fgBlockKey)n.dataset.fgBlockKey=b.key}}
async function init(){let published;if(!preview){try{const r=await fetch(API+'/api/site-content',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)return;published=(await r.json()).content||{};if(!Object.keys(published).length)return}catch{return}}schema=await fetch(preview?'../site-editor-fields.json?v=2':'./site-editor-fields.json?v=2').then(r=>r.json());document.querySelectorAll('.site-logo,.wh-logo,.fg3-logo,.cc-logo,.topbar .logo,.side .logo').forEach(n=>logoOriginals.set(n,n.innerHTML));schema.byKey=new Map(schema.fields.map(f=>[f.key,f]));schema.blockKeys=new Map(schema.blocks.map(b=>[b.key,b]));page=preview?document.body.dataset.fgEditorPage:schema.pages.find(p=>p.file===location.pathname.split('/').pop())?.id||'home';for(const item of [...schema.fields,...schema.blocks])if(applicable(item.page))node(item);if(preview){const defaults={};for(const f of schema.fields.filter(f=>applicable(f.page))){const n=node(f);if(n)defaults[f.key]=value(f,n).trim()}const s=document.createElement('style');s.textContent='[data-fg-field-key]{outline:1px dashed #86a9d0;outline-offset:3px;cursor:text}.fg-editor-selected{outline:3px solid #357ec7!important;outline-offset:4px}[hidden]{display:none!important}';document.head.append(s);document.addEventListener('click',e=>{const n=e.target.closest('[data-fg-field-key],[data-fg-block-key]');if(n)send('fg-editor-select',{key:n.dataset.fgFieldKey||n.dataset.fgBlockKey});if(e.target.closest('a,button,input,select,textarea')){if(!e.target.closest('[contenteditable]'))e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation()},true);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='fg-editor-apply')apply(e.data.content);if(e.data?.type==='fg-editor-focus'){const item=schema.byKey.get(e.data.key)||schema.blockKeys.get(e.data.key);if(item&&applicable(item.page)){const n=node(item);if(n)reveal(n)}}});enable();send('fg-editor-ready',{defaults,page});return}
 apply(published);if(Object.keys(published.fields||{}).length||Object.keys(published.styles||{}).length||Object.keys(published.orders||{}).length){observer=new MutationObserver(mutations=>{if(!mutations.some(m=>!m.target.closest?.('#map,.leaflet-pane,svg')))return;clearTimeout(timer);timer=setTimeout(()=>apply(config),220)});observer.observe(document.body,{childList:true,subtree:true})}}
init().catch(()=>{});
})();
