(()=>{'use strict';
const API='https://floodguard-rescue-backend.onrender.com',el=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n)||0);
async function json(path,token){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(API+path,{headers:token?{Authorization:'Bearer '+token}:{},cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok){const e=Error(d.message||'Chưa tải được voucher.');e.status=r.status;throw e}return d}finally{clearTimeout(timer)}}
async function load(){try{const params=new URLSearchParams(window.location.search),id=params.get('id'),demo=params.get('demo');let v,preview=false;
 if(id){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw Error('Đường dẫn voucher không hợp lệ.');const config=await json('/api/public-config');if(!window.supabase?.createClient)throw Error('Chưa tải được kết nối tài khoản. Hãy tải lại trang.');const auth=window.supabase.createClient(config.supabase.url,config.supabase.anon_key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const session=(await auth.auth.getSession()).data.session;if(!session){el('giftLogin').hidden=false;throw Error('Đăng nhập tài khoản đã đổi voucher rồi mở lại đường dẫn này.')}v=(await json('/api/community/voucher/'+id,session.access_token)).voucher;
 }else if(/^trial-(50|100|200)$/.test(demo||'')){const data=await json('/api/community/rewards');v=data.vouchers.find(x=>x.sku===demo);if(!v)throw Error('Voucher demo này không còn khả dụng.');preview=true;
 }else throw Error('Hãy mở URL quy đổi từ chi tiết voucher của bạn.');
 el('giftStatus').textContent=preview?'Xem trước eGift demo':new Date(v.expires_at)<=new Date()?'Voucher demo đã hết hạn':'✓ Đã nhận eGift demo';el('giftHeading').textContent=preview?'Xem trước voucher demo':'Voucher của bạn đã sẵn sàng';el('giftArtValue').textContent=el('giftValue').textContent=money(v.demo_value_vnd);el('giftExpiry').textContent=preview?v.validity_days+' ngày sau khi đổi':new Date(v.expires_at).toLocaleDateString('vi-VN');el('giftTitle').textContent=v.title;el('giftOrder').textContent=preview?'Đây là bản xem trước. Chưa đổi voucher, chưa trừ điểm.':'Mã đơn: '+v.id+' · Đã đổi '+v.cost+' điểm';el('giftCode').textContent=preview?'FG-DEMO-XEM-TRUOC':v.code;el('giftContent').hidden=false;el('giftMessage').textContent='';
 el('giftCopy').onclick=async()=>{try{await navigator.clipboard.writeText(el('giftCode').textContent);el('giftCopyStatus').textContent='Đã sao chép mã demo.'}catch{el('giftCopyStatus').textContent='Hãy chọn và sao chép mã hiển thị.'}};
 }catch(e){el('giftStatus').textContent='Chưa mở được voucher';el('giftMessage').textContent=['TimeoutError','AbortError'].includes(e.name)?'Kết nối đang chậm. Hãy tải lại trang.':e.message;if(e.status===401)el('giftLogin').hidden=false;}}
load();})();
