/* Isolated fault-injection fixtures only; never loaded by the production app. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.FG_TEST_APP||path.resolve(__dirname,'../app-core.html'),'utf8');
const script=id=>html.match(new RegExp('<script id="'+id+'">([\\s\\S]*?)<\\/script>'))[1];
const routeScript=script('fg-routing-honesty'),geoScript=script('fg81-network-resilience');
const point={lat:10.803,lon:106.733},end={lat:10.776,lon:106.701};
const route={distance:6500,duration:540,geometry:{type:'LineString',coordinates:[[106.733,10.803],[106.72,10.79],[106.701,10.776]]},legs:[{steps:[{name:'Test road',distance:6500,duration:540,geometry:{type:'LineString',coordinates:[[106.733,10.803],[106.701,10.776]]}}]}]};
const response=(data,status=200)=>({ok:status>=200&&status<300,status,headers:{get:()=>null},json:async()=>data});
const timers={setTimeout:(fn,ms)=>setTimeout(fn,ms>=4000?25:0),clearTimeout};
const context=(fetch,extra={})=>{const ctx={window:{},fetch,AbortController,URL,Date,Number,Map,Promise,console,...timers,...extra};vm.createContext(ctx);vm.runInContext(routeScript,ctx);return ctx};
let tests=0;async function check(name,fn){await fn();tests++;console.log('PASS',name)}
(async()=>{
 await check('unavailable backend does not block free geometry or invent ETA',async()=>{const urls=[];const c=context(async u=>{urls.push(u);if(u.includes('traffic-status'))throw Error('network down');return response({code:'Ok',routes:[route]})});c.window.FG31RoutingAPI=()=>{throw Error('must not call traffic on unknown status')};const r=await c.window.FGRouteTraffic(point,end,'car');assert.equal(urls.length,2);assert.equal(r.data.routes[0].duration,null);assert.equal(r.data.routes[0].legs[0].steps[0].duration,null);assert.equal(c.window.FGRouteTime({etaType:'unavailable',duration:9}),'Chưa có thời gian')});
 await check('concurrent identical searches share status and geometry calls',async()=>{const urls=[];const c=context(async u=>{urls.push(u);return response(u.includes('traffic-status')?{configured:false}:{code:'Ok',routes:[route]})});await Promise.all([c.window.FGRouteTraffic(point,end,'car'),c.window.FGRouteTraffic(point,end,'car')]);assert.equal(urls.length,2);await c.window.FGRouteTraffic(point,end,'car');assert.equal(urls.length,2)});
 await check('car service failure switches to backup',async()=>{const urls=[];const c=context(async u=>{urls.push(u);if(u.includes('traffic-status'))return response({configured:false});if(u.includes('router.project-osrm'))return response({},503);return response({code:'Ok',routes:[route]})});const r=await c.window.FGRouteTraffic(point,end,'car');assert.equal(r.data.routes.length,1);assert(urls.some(u=>u.includes('routed-car')))});
 await check('walking backup keeps pedestrian costing',async()=>{let q;const c=context(async u=>{if(u.includes('traffic-status'))return response({configured:false});if(u.includes('routed-foot'))throw Error('network');q=JSON.parse(decodeURIComponent(u.split('?json=')[1]));return response({code:'Ok',routes:[route]})});await c.window.FGRouteTraffic(point,end,'walk');assert.equal(q.costing,'pedestrian')});
 await check('motorbike transient failure retries its own profile, never car',async()=>{let requests=0;const c=context(async u=>{if(u.includes('traffic-status'))return response({configured:false});requests++;assert.equal(JSON.parse(decodeURIComponent(u.split('?json=')[1])).costing,'motor_scooter');if(requests===1)throw Error('temporary network');return response({code:'Ok',routes:[route]})});await c.window.FGRouteTraffic(point,end,'motorbike');assert.equal(requests,2)});
 await check('rate limit is not hammered and provider cooldown applies',async()=>{let n=0;const c=context(async u=>{if(u.includes('traffic-status'))return response({configured:false});n++;return response({},429)});await assert.rejects(c.window.FGRouteTraffic(point,end,'motorbike'));await assert.rejects(c.window.FGRouteTraffic(point,{...end,lon:106.702},'motorbike'));assert.equal(n,1)});
 await check('authentication error cannot trigger geometry fallback',async()=>{let n=0;const c=context(async()=>{n++;return response({configured:true})});c.window.FG31RoutingAPI=async()=>{const e=Error('Login required');e.status=401;throw e};await assert.rejects(c.window.FGRouteTraffic(point,end,'car'),/Login/);assert.equal(n,1)});
 await check('traffic timeout recovers to geometry and timer is bounded',async()=>{const c=context(async u=>response(u.includes('traffic-status')?{configured:true}:{code:'Ok',routes:[route]}));c.window.FG31RoutingAPI=()=>new Promise(()=>{});const r=await c.window.FGRouteTraffic(point,end,'car');assert.equal(r.data.routes[0].etaType,'unavailable')});
 await check('valid traffic ETA is preserved',async()=>{const c=context(async()=>response({configured:true}));c.window.FG31RoutingAPI=async()=>({code:'Ok',routes:[{...route,etaType:'traffic'}]});assert.equal((await c.window.FGRouteTraffic(point,end,'car')).provider,'TomTom');assert.equal(c.window.FGRouteTime({duration:18,etaType:'traffic'}),'18 phút')});
 await check('aborted request returns without waiting for a late provider',async()=>{let finish;const c=context(async u=>u.includes('traffic-status')?response({configured:false}):new Promise(resolve=>{finish=()=>resolve(response({code:'Ok',routes:[route]}))}));const controller=new AbortController(),task=c.window.FGRouteTraffic(point,end,'car',{signal:controller.signal});while(!finish)await new Promise(resolve=>setImmediate(resolve));controller.abort();await assert.rejects(task,e=>e.name==='AbortError');finish();await new Promise(resolve=>setImmediate(resolve))});
 await check('invalid coordinates and malformed geometry never reach map',async()=>{let n=0;const c=context(async u=>{n++;return response(u.includes('traffic-status')?{configured:false}:{code:'Ok',routes:[{...route,geometry:{type:'LineString',coordinates:[[null,1],[2,3]]}}]})});await assert.rejects(c.window.FGRouteTraffic({...point,lat:0},end,'car'));assert.equal(n,0);await assert.rejects(c.window.FGRouteTraffic(point,end,'car'))});
 await check('geocoder drops unsupported language and deduplicates queries',async()=>{const urls=[],c={window:{},Map,Date,Number,Promise,AbortController,console,...timers,fetch:async u=>{urls.push(u);return response({features:[{geometry:{coordinates:[106.72,10.8]},properties:{name:'Test road'}}]})}};vm.createContext(c);vm.runInContext(geoScript,c);await Promise.all([c.window.FG81_NET.searchPlaces('Test road'),c.window.FG81_NET.searchPlaces('Test road')]);assert.equal(urls.length,1);assert(!urls[0].includes('lang=vi'));assert(!urls[0].includes('nominatim'));await c.window.FG81_NET.searchPlaces('Test road');assert.equal(urls.length,1)});
 await check('late geocode cannot overwrite edited endpoints',async()=>{const from={value:'Old start',classList:{remove(){}}},to={value:'Destination',classList:{remove(){}}},pending=[];const c={document:{},$:id=>id==='fg3RouteFrom'?from:to,startPoint:null,endPoint:null,routeRequestSeq:1,Number,Promise,geocode:q=>new Promise(resolve=>pending.push(()=>resolve({...point,label:q}))),drawEndpointMarkers:()=>{throw Error('stale result must not draw')}};vm.createContext(c);const f=html.match(/ async function resolvePoints\(request\).*$/m)[0];vm.runInContext(f,c);const task=c.resolvePoints(1);c.routeRequestSeq++;from.value='New start';pending.forEach(f=>f());await assert.rejects(task,e=>e.name==='AbortError');assert.equal(c.startPoint,null);assert.equal(c.endPoint,null)});
 await check('cancel releases button; old request cannot repaint or relock new search',async()=>{let firstResolve;const calls=[],btn={disabled:false,setAttribute(){},removeAttribute(){}},inputs={fg3RouteRun:btn,fg3RouteRain:{value:100},fg3RouteFrom:{classList:{remove(){}}},fg3RouteTo:{classList:{remove(){}}}};const c=context(async()=>response({configured:false}));Object.assign(c,{$:id=>inputs[id],routeRequestSeq:0,routeRunController:null,autoRunTimer:null,travelMode:'car',ROUTE_MODES:{car:{icon:'car',label:'Ô tô'}},lastRoutes:[],routeSessionReady:false,results:{innerHTML:''},status:{addEventListener(){}},hideSuggestions(){},fg70Publish(){},clearRouteVisuals(){c.lastRoutes=[]},setRouteTools(){},showStatus(...x){calls.push(x)},esc:String,resolvePoints:n=>n===1?new Promise(resolve=>{firstResolve=resolve}):Promise.resolve([point,end]),analyzeRoute:r=>({route:r,travelMode:'car',index:0}),recommendedFor:x=>x[0],drawRoutes:x=>{calls.push(['draw',x[0].route.distance])},renderResults(){},updateRouteSummary(){},fg19MobileMapReveal(){}});c.window.FGRouteTraffic=async()=>({provider:'test',data:{code:'Ok',routes:[route]}});const begin=html.indexOf(' async function run(isAutoModeSwitch=false)'),finish=html.indexOf('\n function fg70Publish',begin);vm.runInContext(html.slice(begin,finish),c);vm.runInContext(html.match(/ function cancelPendingRoute\(\).*$/m)[0],c);const old=c.run();assert(btn.disabled);c.cancelPendingRoute();assert.equal(btn.disabled,false);await c.run();const drawCount=calls.filter(x=>x[0]==='draw').length;firstResolve([point,end]);await old;assert.equal(calls.filter(x=>x[0]==='draw').length,drawCount);assert.equal(drawCount,1);assert.equal(btn.disabled,false)});
 await check('a failed refresh retains the previous route and restores controls',async()=>{const btn={disabled:false,setAttribute(){},removeAttribute(){}},inputs={fg3RouteRun:btn,fg3RouteRain:{value:100},fg3RouteFrom:{classList:{remove(){}}},fg3RouteTo:{classList:{remove(){}}}};let cleared=0,tools=false,lastStatus='';const oldRoute={route,index:0,travelMode:'car'};const c=context(async()=>response({configured:false}));Object.assign(c,{$:id=>inputs[id],routeRequestSeq:0,routeRunController:null,autoRunTimer:null,travelMode:'car',ROUTE_MODES:{car:{icon:'car',label:'Ô tô'}},lastRoutes:[oldRoute],routeSessionReady:true,results:{innerHTML:'Previous route'},status:{addEventListener(){}},hideSuggestions(){},fg70Publish(){},clearRouteVisuals(){cleared++},setRouteTools:v=>{tools=v},showStatus:v=>{lastStatus=v},esc:String,resolvePoints:async()=>[point,end],console:{error(){}},fg19MobileMapReveal(){}});c.window.FGRouteTraffic=async()=>{throw Error('Offline')};const begin=html.indexOf(' async function run(isAutoModeSwitch=false)'),finish=html.indexOf('\n function fg70Publish',begin);vm.runInContext(html.slice(begin,finish),c);await c.run();assert.equal(cleared,0);assert.equal(c.lastRoutes[0],oldRoute);assert.equal(c.results.innerHTML,'Previous route');assert.equal(btn.disabled,false);assert.equal(tools,true);assert(lastStatus.includes('data-route-retry'));assert(lastStatus.includes('Đang giữ lộ trình trước đó'))});
 console.log('All '+tests+' fault-injection and lifecycle checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
