const {JSDOM,requestInterceptor}=require('../editor-tools/node_modules/jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const schema=JSON.parse(fs.readFileSync(root+'/site-editor-fields.json'));
for(const page of schema.pages){const doc=new JSDOM(fs.readFileSync(root+'/editor-preview/'+page.id+'.html','utf8')).window.document;assert.equal(doc.querySelectorAll('script').length,1);assert.ok(!doc.querySelector('[onclick],meta[http-equiv="refresh"]'));for(const f of schema.fields.filter(x=>x.page===page.id))assert.ok(doc.querySelector(f.selector),f.key);for(const b of schema.blocks.filter(x=>x.page===page.id))assert.ok(doc.querySelector(b.selector),b.key)}
const resources={interceptors:[requestInterceptor(request=>{const u=new URL(request.url);let f=path.join(root,u.pathname.replace(/^\//,'')||'index.html');if(fs.existsSync(f))return new Response(fs.readFileSync(f,'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''),{headers:{'Content-Type':f.endsWith('.css')?'text/css':'text/html'}});return new Response('',{status:404})})]};
let state={draft:{},published:{},revision:0,has_previous:false},previous;
const dom=new JSDOM(fs.readFileSync(root+'/site-editor.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''),{url:'https://test.local/site-editor.html',resources,runScripts:'dangerously',pretendToBeVisual:true});const w=dom.window,$=id=>w.document.getElementById(id),response=d=>({ok:true,json:async()=>d});
w.structuredClone=structuredClone;w.AbortSignal.timeout=()=>undefined;w.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'mock'}}})}})};w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.fetch=async(url,opts)=>{if(url.includes('fields.json'))return response(schema);if(url.includes('public-config'))return response({supabase:{url:'https://mock.local',anon_key:'mock'}});if(opts?.method==='POST'){const b=JSON.parse(opts.body);assert.equal(b.revision,state.revision);if(b.action==='publish'){previous=state.published;state.published=b.content;state.has_previous=true}if(b.action==='restore'){state.draft=previous;state.published=previous}else state.draft=b.content;state.revision++}return response(JSON.parse(JSON.stringify(state)))};
$('preview').addEventListener('load',()=>{const fw=$('preview').contentWindow;fw.HTMLElement.prototype.scrollIntoView=()=>{};fw.fetch=async()=>response(schema);fw.document.execCommand=()=>{};w.postMessage=d=>w.dispatchEvent(new w.MessageEvent('message',{data:d,origin:w.location.origin,source:fw}));fw.postMessage=d=>fw.dispatchEvent(new fw.MessageEvent('message',{data:d,origin:w.location.origin,source:w}));fw.eval(fs.readFileSync(root+'/site-content.js','utf8'))});
const wait=async f=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,10))}throw Error('wait failed')};
(async()=>{w.eval(fs.readFileSync(root+'/site-editor.js','utf8'));await wait(()=>!$('workspace').hidden);$('page').value='about';$('page').dispatchEvent(new w.Event('change'));await wait(()=>$('preview').contentDocument.querySelector('[data-fg-field-key="about.title"]'));
const fw=$('preview').contentWindow,n=fw.document.querySelector('[data-fg-field-key="about.title"]');n.textContent='<img onerror=evil()> Giới thiệu mới';n.dispatchEvent(new fw.Event('input'));$('fieldList').value='about.title';$('fieldList').dispatchEvent(new w.Event('change'));assert.equal($('fieldValue').value,n.textContent);assert.equal(n.querySelector('img'),null);
$('node-color').value='#123456';$('node-color').dispatchEvent(new w.Event('change'));assert.equal(fw.getComputedStyle(n).color,'rgb(18, 52, 86)');$('save').click();await wait(()=>state.revision===1&&!$('save').disabled);assert.deepEqual(state.published,{});$('publish').click();$('acceptConfirm').click();await wait(()=>state.revision===2&&!$('save').disabled);assert.equal(state.published.fields['about.title'],n.textContent);
const check=$('chapterList').querySelector('input');check.checked=false;check.dispatchEvent(new w.Event('change'));assert.equal(fw.document.getElementById('chapter-1').hidden,true);$('chapterList').querySelectorAll('button')[1].click();assert.equal(fw.document.querySelector('.about-chapter').id,'chapter-2');$('mobile').click();assert.ok($('preview').classList.contains('mobile'));
$('restore').click();$('acceptConfirm').click();await wait(()=>state.revision===3&&!$('save').disabled);assert.deepEqual(state.published,{});
$('page').value='contact';$('page').dispatchEvent(new w.Event('change'));await wait(()=>$('preview').contentDocument.querySelector('[data-fg-field-key="contact.email"]'));$('fieldList').value='contact.email';$('fieldList').dispatchEvent(new w.Event('change'));const email=$('fieldValue');email.value='test@example.com';email.dispatchEvent(new w.Event('input'));assert.equal($('preview').contentDocument.querySelector('.fg-contact-address').href,'mailto:test@example.com');const mixed=schema.fields.find(f=>f.page==='community'&&Number.isInteger(f.textIndex)&&f.selector.includes('cg-consent'));if(mixed)assert.ok(mixed); assert.equal($('page').querySelectorAll('option').length,20);
$('page').value='about';$('page').dispatchEvent(new w.Event('change'));await wait(()=>$('preview').contentDocument.querySelector('[data-fg-field-key="about.title"]'));
const chapterBlock=schema.blocks.find(b=>b.page==='about'&&b.selector==='[id="chapter-3"]');assert.ok(chapterBlock);$('element').value=chapterBlock.key;$('element').dispatchEvent(new w.Event('change'));$('moveUp').click();assert.deepEqual([...$('preview').contentDocument.querySelectorAll('.about-chapter')].map(n=>n.id),['chapter-1','chapter-3','chapter-2','chapter-4']);$('fieldList').value='about.chapter3.title';$('fieldList').dispatchEvent(new w.Event('change'));$('fieldValue').value='Tiêu đề phần ba mới';$('fieldValue').dispatchEvent(new w.Event('input'));assert.equal($('preview').contentDocument.querySelector('#chapter-3 h3').textContent,'Tiêu đề phần ba mới');
for(const p of ['community','app','admin','accounts','sosAdmin']){$('page').value=p;$('page').dispatchEvent(new w.Event('change'));await wait(()=>$('preview').contentDocument.body?.dataset.fgEditorPage===p&&$('preview').contentDocument.querySelector('[data-fg-field-key]'));assert.ok($('fieldList').options.length>0)}
$('page').value='community';$('page').dispatchEvent(new w.Event('change'));await wait(()=>$('preview').contentDocument.querySelector('[data-fg-field-key]'));const submit=schema.fields.find(f=>f.page==='community'&&f.type==='text'&&f.selector==='[id="cgSubmit"]');assert.ok(submit);$('fieldList').value=submit.key;$('fieldList').dispatchEvent(new w.Event('change'));const form=$('preview').contentDocument.querySelector('#cgForm'),button=form.querySelector('#cgSubmit'),input=form.querySelector('#cgConsent');let bound=0;button.addEventListener('custom-test',()=>bound++);$('fieldValue').value='Gửi thông tin ngập';$('fieldValue').dispatchEvent(new w.Event('input'));button.dispatchEvent(new ($('preview').contentWindow.Event)('custom-test'));assert.equal(bound,1);assert.equal(form.querySelector('#cgConsent'),input);assert.equal(button.type,'submit');assert.equal(button.textContent.trim(),'Gửi thông tin ngập');
assert.equal($('page').querySelectorAll('option').length,20);console.log('PASS: 20-page catalogs, direct text edits, styles, draft isolation, publishing, restoration, general layout ordering, stable targets, app/admin/community previews, preserved form nodes/events, mobile toggle and contact email');dom.window.close()})().catch(e=>{console.error(e);dom.window.close();process.exit(1)});
