const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),old=JSON.parse(fs.readFileSync(root+'/site-editor-fields.json'));
old.fields=old.fields.filter(f=>!/^.+\.(?:n\d+|e[0-9a-f]{16})\./.test(f.key));
const pages=[['home','index.html','Trang chủ','Công khai'],['login','index.html','Đăng nhập / đăng ký','Ứng dụng'],['problem','problem.html','Vấn đề ngập lụt','Công khai'],['features','features.html','Tính năng & EV','Công khai'],['how','how-it-works.html','Cách hoạt động','Công khai'],['alerts','alerts.html','Cảnh báo','Công khai'],['rescue','rescue.html','Giới thiệu cứu hộ','Công khai'],['about','about.html','Giới thiệu','Công khai'],['data','data.html','Dữ liệu','Công khai'],['faq','faq.html','Câu hỏi thường gặp','Công khai'],['contact','contact.html','Liên hệ','Công khai'],['model','model-evaluation.html','Đánh giá mô hình','Công khai'],['app','app-core.html','Bản đồ & công cụ ứng dụng','Ứng dụng'],['community','community.html','Báo cáo, điểm & huy hiệu','Ứng dụng'],['voucher','voucher.html','Trang voucher','Ứng dụng'],['rescueTeam','rescue-team.html','Ứng dụng đội cứu hộ','Ứng dụng'],['admin','admin.html','Tổng quan quản trị & kho ảnh','Quản trị'],['accounts','accounts.html','Quản lý tài khoản','Quản trị'],['rescueTeams','rescue-teams.html','Quản lý đội cứu hộ','Quản trị'],['sosAdmin','sos-admin.html','Quản lý SOS','Quản trị']].map(([id,file,label,group])=>({id,file,label,group}));
const fields=[...old.fields],blocks=[],previewDir=root+'/editor-preview';fs.mkdirSync(previewDir,{recursive:true});
function template(source){const chunks=[];for(let i=0;i<source.length;i++){if(source[i]!=='`')continue;let html='';for(i++;i<source.length;i++){if(source[i]==='\\'){html+=source.slice(i,i+2);i++;continue}if(source[i]==='`')break;if(source[i]==='$'&&source[i+1]==='{'){i+=2;let depth=1,quote='';for(;i<source.length&&depth;i++){const c=source[i];if(quote){if(c==='\\'){i++;continue}if(c===quote)quote='';continue}if(c==='"'||c==="'"||c==='`'){quote=c;continue}if(c==='{')depth++;if(c==='}')depth--}i--;continue}html+=source[i]}if(/<[a-z][\s\S]*>/i.test(html))chunks.push(html)}
for(const m of source.matchAll(/\.innerHTML\s*=\s*('(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*")/g)){let h;try{h=require('vm').runInNewContext(m[1],{}, {timeout:100})}catch{continue}if(/<[a-z]/i.test(h))chunks.push(h)}return chunks}
const extras={community:['community.js'],app:[],admin:['admin-report-photos.js','admin-insights.js']};
function cssPath(el){if(el.id)return '[id="'+el.id.replace(/["\\]/g,'\\$&')+'"]';const parts=[];let n=el;while(n&&n.tagName!=='BODY'&&n.tagName!=='HTML'){const cls=[...n.classList].filter(x=>/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(x));const classSelector=cls.map(x=>'.'+x).join('');if(!n.id&&classSelector&&n.ownerDocument.querySelectorAll(classSelector).length===1){parts.unshift(classSelector);break}if(n.id){parts.unshift('[id="'+n.id.replace(/["\\]/g,'\\$&')+'"]');break}let index=1;for(let p=n.previousElementSibling;p;p=p.previousElementSibling)if(p.tagName===n.tagName)index++;parts.unshift(n.tagName.toLowerCase()+':nth-of-type('+index+')');n=n.parentElement}return parts.join(' > ')}
for(const page of pages){const source=fs.readFileSync(root+'/'+page.file,'utf8'),doc=new JSDOM(source).window.document;
const scripts=[...doc.querySelectorAll('script')].map(n=>n.textContent);for(const name of extras[page.id]||[])scripts.push(fs.readFileSync(root+'/'+name,'utf8'));
for(const script of scripts)for(const html of template(script)){const t=doc.createElement('template');t.innerHTML=html;for(const child of [...t.content.children]){if(child.tagName==='STYLE'){doc.head.appendChild(child);continue}const ids=[child,...child.querySelectorAll('[id]')].filter(n=>n.id);if(!ids.length||ids.every(n=>doc.getElementById(n.id)))continue;for(const n of [...child.querySelectorAll('[id]')])if(doc.getElementById(n.id))n.remove();if(child.id&&doc.getElementById(child.id))continue;doc.body.appendChild(child)}}
const seen=new Set();for(const n of doc.querySelectorAll('[id]')){if(seen.has(n.id))n.remove();else seen.add(n.id)}
for(const n of doc.querySelectorAll('script,meta[http-equiv="refresh"],iframe,object,embed'))n.remove();for(const el of doc.querySelectorAll('*'))for(const a of [...el.attributes])if(/^on/i.test(a.name))el.removeAttribute(a.name);
if(page.id==='home'){doc.querySelector('#authScreen')?.remove();doc.querySelector('#appView')?.remove()}if(page.id==='login'){doc.querySelector('#fgWebsiteHome')?.remove();doc.querySelector('#appView')?.remove()}
if(page.id==='community'||page.id==='app'){let panel=doc.querySelector('[data-community-page]');if(!panel){panel=doc.createElement('dialog');panel.className='cg-panel';doc.body.append(panel)}else panel.className='cg-panel cg-page';const cg=[...doc.querySelectorAll('.cg-head')][0],scroll=[...doc.querySelectorAll('.cg-scroll')][0];if(cg)panel.append(cg);if(scroll)panel.append(scroll)}
const legacy=new Map(old.fields.filter(f=>f.page===page.id).map(f=>[doc.querySelector(f.selector),f]));let serial=0;const registered=new Set(fields.filter(f=>f.page===page.id).map(f=>f.selector));
for(const el of [...doc.body.querySelectorAll('*')]){if((el.tagName==='OPTION'&&!el.hasAttribute('value'))||el.closest('script,style,svg,code,pre')||el.tagName==='TEMPLATE')continue;const selector=cssPath(el);if(!selector)continue;
const dynamic=/count|points|earned|balance|expiry|code$|status|message|risk$|depth$|lat$|lon$|location$|preview|photofull|photodetail|giftvalue|giftartvalue/i.test(el.id)||el.matches('[role="status"],[role="alert"],[aria-live]');
const base=page.id+'.e'+require('crypto').createHash('sha256').update(selector).digest('hex').slice(0,16),group=el.closest('header,nav,footer,aside')?.tagName==='NAV'?'Navigation':el.closest('footer')?'Chân trang':el.closest('header')?'Đầu trang':'Nội dung';
const existing=legacy.get(el);let used=!!existing;
if(!dynamic){for(let i=0;i<el.childNodes.length;i++){const t=el.childNodes[i];if(t.nodeType!==3||!/[A-Za-zÀ-ỹ]/.test(t.nodeValue)||t.nodeValue.trim().length<2)continue;if(existing)continue;if(el.closest('[contenteditable]'))continue;const value=t.nodeValue.trim();if(value.length>8000)continue;fields.push({key:base+'.t'+i,page:page.id,type:'text',selector,textIndex:i,label:value.slice(0,75),group,max:8000,default:value});used=true}
 if(el.matches('input[placeholder],textarea[placeholder]')){fields.push({key:base+'.placeholder',page:page.id,type:'placeholder',selector,label:'Ô nhập: '+el.getAttribute('placeholder'),group,max:300,default:el.getAttribute('placeholder')});used=true}
 if(el.matches('a[href]')&&/^(https?:|mailto:|tel:|\.\/|\/|#)/.test(el.getAttribute('href'))){fields.push({key:base+'.link',page:page.id,type:'link',selector,label:'Liên kết: '+el.textContent.trim().slice(0,50),group,max:2048,default:el.getAttribute('href')});used=true}
 if(el.matches('img[src]')&&!el.id.match(/photo|preview|station|gift/i)&&!/\$\{/.test(el.getAttribute('src'))){fields.push({key:base+'.image',page:page.id,type:'image',selector,label:'Ảnh: '+(el.alt||el.id||'Hình trên trang'),group,max:300000,default:el.getAttribute('src')});used=true}}
if(used||el.matches('section,article,main,header,footer,nav,aside,form,dialog')||el.matches('div[id],div[class*="card"],div[class*="panel"],div[class*="grid"]'))blocks.push({key:existing?.key||base,page:page.id,selector:existing?.selector||selector,label:(el.textContent.trim().replace(/\s+/g,' ').slice(0,75)||el.id||el.className||el.tagName),tag:el.tagName.toLowerCase(),parent:cssPath(el.parentElement)});}
const policy=doc.createElement('meta');policy.httpEquiv='Content-Security-Policy';policy.content="default-src 'self' https: data:; script-src 'self'; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data:; object-src 'none'; form-action 'none'; base-uri 'self'";doc.head.prepend(policy);const b=doc.createElement('base');b.href='../';doc.head.prepend(b);const s=doc.createElement('style');s.textContent='body{min-height:100vh}#login,#gate,.fg34-auth-overlay{display:none!important}#fgWebsiteHome{position:relative!important;inset:auto!important}#authScreen{position:relative!important}#map:empty{background:linear-gradient(135deg,#e7eff4,#d6e5ed);min-height:360px}body[data-fg-editor-page="community"] .cg-panel{display:block;max-height:none;margin:auto}';doc.head.append(s);doc.body.dataset.fgEditorPage=page.id;const runtime=doc.createElement('script');runtime.src='../site-content.js?v=2';doc.body.append(runtime);fs.writeFileSync(previewDir+'/'+page.id+'.html','<!doctype html>\n'+doc.documentElement.outerHTML);
}
const schema={version:2,pages,fields,blocks};fs.writeFileSync(root+'/site-editor-fields.json',JSON.stringify(schema));if(process.env.FG_EDITOR_BACKEND_DIR)fs.writeFileSync(path.join(process.env.FG_EDITOR_BACKEND_DIR,'site-editor-fields.json'),JSON.stringify(schema));console.log(JSON.stringify({pages:pages.length,fields:fields.length,blocks:blocks.length,byPage:pages.map(p=>({page:p.id,fields:fields.filter(f=>f.page===p.id).length}))}));
